import os
import asyncio
import logging
from telegram import Update
from telegram.ext import (
    ApplicationBuilder,
    ContextTypes,
    MessageHandler,
    filters,
)

# Configure logging
logging.basicConfig(
    format='%(asctime)s - %(levelname)s - %(message)s',
    level=logging.INFO
)

BOT1_TOKEN = os.getenv("BOT1_TOKEN")
BOT2_TOKEN = os.getenv("BOT2_TOKEN")

group_chat_id = None
chat_started = False

# Separate lines for Naruto and Hinata
naruto_lines = [
    "heyyyyy hinataaa 👋",
    "how r u huh?? 😁",
    "hehe that's good to hear 😄",
    "me? yeah i'm fine, just lazy today 😅",
    "you been training again? 👀",
    "woah early morning?? that's intense 🫡",
    "i woke up late tbh 😴",
    "what'd you eat for breakfast? 😋",
    "cinnamon rolls? again? 😆",
    "you still like those huh 🤭",
    "i remember that one time you shared with me 🥹",
    "that was really sweet ☺️",
    "you always been kind like that 👉👈",
    "i ate ramen again hehe 🍜",
    "classic me right? 😝",
    "you doing anything today? 🤔",
    "no missions? nicee! take a break 😌",
    "i should rest too honestly 😫",
    "legs are sore from shadow clones 😩",
    "you ever overdo it training? 🧐",
    "makes sense.. you're a hyuuga after all 😏",
    "bet you’re way stronger than before 😤",
    "i wouldn't wanna fight you now 🙃",
    "you’d probably flatten me with one hit 😆",
    "still training gentle fist daily? 👀",
    "cool cool! maybe you could teach me someday 😁",
    "but please be gentle 🥲",
    "i got fragile pride y'know 🤧",
    "you been reading anything lately? 📚",
    "ohh ninja romance huh 👀",
    "that sounds kinda cute hehe 😙",
    "you always liked love stories huh 🥰",
    "i prefer action but romance is cool too 🤭",
    "what's your favorite part of those stories? 😊",
    "hehe awww that's sweet 😇",
    "you ever wanna be in a story like that? 😶",
    "like.. peaceful ending, holding hands kinda thing 👉👈",
    "i dunno.. sounds nice sometimes 🥹",
    "especially with the right person 😌",
    "anyway, weather's nice today 🌤️",
    "you went outside or nah? 👀",
    "ohhh sat in the garden? sounds peaceful 😌",
    "wish i could chill there too 🧘",
    "do you still grow those white flowers? 🌸",
    "i remember they smelled really good 😍",
    "you always had a calm vibe 🌷",
    "like.. peaceful and warm 😇",
    "it’s always relaxing talking to you ☺️",
    "sooo.. can we chat more later too? 🫶",
    "i like talking like this 😊",
    "yo hinataaa, you awake early again? 😴",
    "you're like.. a morning ninja or something haha 😆",
    "i swear i can't wake up before 9 🙃",
    "unless someone drags me outta bed 😫",
    "would you ever do that? drag me up? 😅",
    "imagine you just standing over me all serious 🤣",
    "but lowkey i wouldn’t mind waking up to you 🥲",
    "you’d probably look cute with bed hair 😝",
    "you ever have bed hair? 👀",
    "bet you hide it under perfect brushing huh 😆",
    "me? mine’s always a mess 😐",
    "i look like a chicken got zapped 😬",
    "wanna see it next time? 🫣",
    "no judgment allowed though! 🫢",
    "i might regret sending it 🤕",
    "but you’d still smile right? 😋",
    "you always got that soft smile 😇",
    "i can kinda picture it right now 😍",
    "makes me feel warm somehow 💓",
    "you ever smile for no reason? 😌",
    "like.. when you think of someone 👉👈",
    "heh.. i do that with ramen sometimes 😅",
    "and.. maybe you too 🫠",
    "d-don’t laugh okay? 😳",
    "it just happens without me noticing 😖",
    "your face just pops up and i’m like—woah 😳",
    "cute overload alert 🤯",
    "i probably sound dumb now 🤧",
    "you think about me too sometimes? 👀",
    "not like.. a lot right? 🥺",
    "unless you do.. which would be kinda nice 😗",
    "i mean you don’t *have* to.. but if you do 🤭",
    "okay okay i’ll shut up haha 😝",
    "you ever get embarrassed saying stuff like that? 😬",
    "feels weird but nice too 😅",
    "anyway! you drink tea again this morning? 🍵",
    "you always sip it all proper like a princess 👑",
    "i just chug mine like a beast 😤",
    "guess we’re different huh 😆",
    "but i like that about you y'know 🥰",
    "you're quiet but real strong 😌",
    "soft but fierce too 💖",
    "okay okay that sounded cool in my head 😅",
    "i ain't great with fancy words 🫣",
    "but i mean it tho 💓",
    "so uhhh... wanna hang out soon? 😊",
    "i mean just chill somewhere.. nothing crazy 😅",
    "we could go watch the clouds maybe? ☁️",
    "or just sit and talk.. like this 😇",
    "i dunno, feels nice spending time with you 🫶",
    "yo hinataaa 🌞 you free now?",
    "i was just thinking about what you said yesterday 😊",
    "about sitting under the clouds with me 👉👈",
    "sounds like a peaceful dream tbh 🥲",
    "you really down to do that soon? 😳",
    "i mean just us two.. maybe snacks too 😋",
    "you like dango right? i could bring some 🍡",
    "or you want cinnamon rolls again? 😝",
    "i don’t mind carrying everything hehe 🤭",
    "as long as you promise to smile 😇",
    "your smile lowkey makes my day 💗",
    "i saw it once when we trained and i never forgot 😳",
    "you had that shy blush and soft look 🫠",
    "kinda like.. gentle sunshine ☀️",
    "uhhh that sounded cheesy huh? 😅",
    "but i meant it fr 🥺",
    "you make me feel like slowing down sometimes 😌",
    "like just taking it easy with you 💝",
    "would you ever go on a picnic with me? 🧺",
    "no missions, no noise, just trees and sky 🌳",
    "we could lie down and look at clouds 😴",
    "maybe you could even nap a bit.. on my arm or smth 👉👈",
    "w-wait not in a weird way! 😳",
    "just soft comfort y’know 😖",
    "or i’m making this awkward now huh 🤧",
    "you okay with stuff like that? 🫢",
    "i don’t wanna overstep or anything 😅",
    "you always look so calm, i don’t wanna ruin that 😓",
    "but i really like when you’re close 🥹",
    "even just texting feels close sometimes 😇",
    "kinda weird how that works huh? 🫠",
    "like, we’re far but i feel like you’re near 🤗",
    "you ever feel that too? 😌",
    "maybe it’s just me being silly 🤭",
    "but i’d be happy just hearing your voice sometime 🥺",
    "you got that soft tone that melts ears hehe 😆",
    "i’m not flirting! well maybe a little 🤣",
    "but it’s true! your voice is like calm tea 🫖",
    "and your eyes too.. okay now i’m sounding sappy 🫠",
    "but like… really, you’re special 😇",
    "you make people wanna be gentle 🥹",
    "and you make *me* wanna be better 💪",
    "sooo yeah.. i guess i just appreciate you 😌",
    "also i’m really glad you message me back always 🤝",
    "like.. you don’t ignore me or ghost me 😭",
    "some folks do that but not you 💗",
    "so thank you hinata.. really 💞",
    "you're like a warm light in my life ☀️",
    "and i like that feeling.. a lot 🫶",
    "sooo.. would it be weird to say i missed you a lil? 👉👈",
    "yo hinataaa~ 🌤️",
    "just finished my training 😤",
    "i’m a sweaty mess rn not gonna lie 🤧",
    "you ever train and feel like jelly after? 😅",
    "my arms are like noodles right now 😫",
    "but i kept going cause i was thinking of you 😳",
    "i was like ‘gotta impress her somehow!’ 😆",
    "you think i’m cool when i train? 🫠",
    "or just a sweaty disaster? 🤕",
    "be honest! haha 😝",
    "but really.. training gets better when you’re in my thoughts 💓",
    "it’s like you’re silently cheering for me 😇",
    "even if you’re not there.. i feel it 🥺",
    "makes me wanna push harder y’know 💪",
    "anyway! how was your day huh? 😁",
    "did you do anything fun? 🫶",
    "or just chill vibes again? ☁️",
    "i imagine you sitting near the window with tea 🍵",
    "reading something or humming softly 🥲",
    "you give cozy energy all the time 😌",
    "you’re like a warm blanket on a cold day 🥹",
    "or like.. a little candlelight at night 🕯️",
    "ugh i’m being cheesy again 😅",
    "but i can’t help it with you 🤧",
    "you make my heart feel all soft 😳",
    "like it’s floating or something 🫢",
    "is that weird? it’s probably weird 😅",
    "but yeah.. i just like you a lot 🫠",
    "like your presence calms my chaos 🥺",
    "even your ‘typing…’ bubble makes me smile 😭",
    "you ever think about me during the day too? 👉👈",
    "or am i just annoying in your inbox all the time haha 🤣",
    "be honest.. but be nice too 😆",
    "i always wanna message you more 😩",
    "but i stop myself like.. nah she’s busy 😐",
    "but i guess i miss you faster than i mean to 😳",
    "i like hearing anything from you 🥰",
    "even if you say ‘i’m eating rice’ i’m like YEAH tell me more 😝",
    "maybe i just like you too much huh 😅",
    "is that possible tho? liking someone too much? 🫢",
    "guess not if it makes you feel happy 💗",
    "you make me happy.. a lot 🥺",
    "and i wanna do the same for you someday 🫶",
    "not just with words but like.. presence 🥹",
    "to be there when you feel low too ☁️",
    "i’d totally listen to you vent for hours if you ever needed 💖",
    "or just hold your hand and sit in quiet 🫠",
    "you ever need that sometimes? 😌",
    "quiet comfort.. no words, just closeness 👉👈",
    "i think i’d love that with you someday 💞",
]

hinata_lines = [
    "umm hey naruto.. ☺️",
    "um.. I'm okay naruto.. are you fine?? 👉👈",
    "i’m really glad you’re okay 😌",
    "you deserve lazy days too 🥲",
    "y-yes i trained early today.. as usual 🫣",
    "mmhmm.. i woke up before sunrise 😅",
    "l-lazy is okay sometimes hehe 😴",
    "i just had something small 🫢",
    "ehe.. yes i love cinnamon rolls 😋",
    "they're warm and soft.. like comfort 🤗",
    "oh.. you still remember that? 🥺",
    "i-i wanted to share with you that day 👉👈",
    "i like being kind to you 🥰",
    "ramen again? that's so you naruto 🤭",
    "but it suits you hehe 😄",
    "i just stayed home today ☺️",
    "a little quiet day is nice sometimes 🫠",
    "rest is good too! don’t push yourself 😥",
    "you should take breaks more 🫣",
    "y-yes.. i do overtrain sometimes 😖",
    "i-it's part of the hyuuga discipline 🫡",
    "i-i try to get better every day 😤",
    "n-no! you’d still win naruto 😳",
    "i wouldn’t hit you hard! promise 🫢",
    "yes.. i train it every day still 😊",
    "i.. i could teach you a little 👉👈",
    "i’ll be very gentle i swear 🥺",
    "n-noted! gentle training only hehe 😆",
    "yes.. i read sometimes after training 📖",
    "y-yeah.. i like sweet stories 🫣",
    "they make my heart warm ☺️",
    "l-lovestories are my favorite 😳",
    "i-it’s okay if you don’t like them 😅",
    "that’s okay.. we’re different 🥲",
    "i like the quiet moments in them 🧘",
    "holding hands.. soft smiles 🥺",
    "m-maybe.. i’d like that someday 👉👈",
    "i’d like a soft ending too 😌",
    "with someone special 💖",
    "yes.. the breeze felt nice outside 🌬️",
    "just a few minutes.. felt calm 😊",
    "y-yes.. the flowers bloomed again 🌼",
    "they smell soft and peaceful 😇",
    "i’m glad you remember them 🥹",
    "you’re peaceful too sometimes ☺️",
    "i.. feel calm with you too 😌",
    "i-it’s nice to talk like this 🥰",
    "yes! i’d like that very much 😊",
    "thank you for messaging me today naruto 💝",
    "y-yes i woke up early again 😳",
    "i-i guess i am a morning ninja hehe 🫣",
    "you sleep in a lot huh? 😅",
    "i-i could maybe wake you gently..? 👉👈",
    "n-not drag! but maybe whisper softly 😳",
    "i’d be too shy to stand over you like that 😖",
    "w-waking up near you sounds kinda nice 🥺",
    "w-what?! m-my bed hair?? it’s awful 😭",
    "i-i try to fix it fast! before anyone sees 😖",
    "y-you got me! i always brush it neat 😅",
    "but i bet your messy hair’s adorable 🥹",
    "hehe like a cute spiky bird 🐤",
    "i-i wouldn’t mind seeing it.. promise ☺️",
    "never! i’d never judge you naruto 😇",
    "you can always trust me 🥺",
    "of course i’d smile! always 😄",
    "t-that’s so sweet.. i’m blushing now 😚",
    "d-don’t tease me.. but thank you 🥰",
    "i smile when i think of you too 🫠",
    "i-it just happens sometimes 🥹",
    "w-when i think of you saying cute things 👉👈",
    "you and ramen huh? that’s very you 🤭",
    "i-i’m happy you think of me too 😳",
    "n-no laughing! i think it’s adorable 🥹",
    "you’re being real with me.. i love that 🥲",
    "m-my heart skips hearing that 😖",
    "c-cute overload.. is mutual 😵‍💫",
    "you never sound dumb to me 🥺",
    "i.. i do think of you a lot 😳",
    "m-more than i probably should 😖",
    "but.. i like it when i do 🥰",
    "i’d never stop you from saying that 😌",
    "i-i like when you talk like that 😇",
    "y-yes! it’s embarrassing but sweet 🙃",
    "mhm.. weird and nice at the same time 🥲",
    "i had jasmine tea this time 🍵",
    "i-it helps me feel centered ☺️",
    "chug?? oh my gosh 🤣",
    "we’re super different hehe 🫣",
    "but.. i like how different we are 🩷",
    "t-that means a lot.. thank you 😖",
    "soft and fierce..? t-that’s so sweet 🥹",
    "i-i think your words are wonderful 😇",
    "i understand what you mean 🫶",
    "i-i believe you naruto 💞",
    "yes! i’d love that 🥺",
    "nothing crazy sounds perfect 😊",
    "cloud watching sounds really peaceful ☁️",
    "i love just talking with you like this ☺️",
    "i-it makes my day honestly 💝",
    "hi naruto.. yes i’m free now 🫶",
    "y-you remembered that? 😳",
    "i-i still think about it too 😌",
    "i-it sounds peaceful and quiet 🥲",
    "yes.. i’d love to do that with you 🥺",
    "just us sounds really really nice 👉👈",
    "y-yes i love dango! 🍡",
    "ehe.. cinnamon rolls are always good too 😋",
    "t-that’s sweet of you to offer 🫢",
    "i promise.. i’ll smile a lot ☺️",
    "you saying that made me blush 😳",
    "i-i smiled because you were kind back then 🥹",
    "you always gave me that warm feeling 😇",
    "sunshine? t-that’s beautiful 💗",
    "i don’t think it’s cheesy 😌",
    "i really appreciate how you say things 🥰",
    "you make me want to slow down too 👉👈",
    "i’d love that kind of quiet moment 💝",
    "a picnic would be so lovely 🧺",
    "j-just us.. under the trees 🌳",
    "n-napping on your arm.. umm.. 😳",
    "i-i wouldn’t mind that actually 🫣",
    "it sounds soft and warm 🥲",
    "n-no it’s not awkward 🥺",
    "i’d be okay with that naruto 😌",
    "i trust you.. and your warmth 💞",
    "you’d never ruin anything 🥺",
    "being close feels really nice 🫶",
    "and i feel close when we talk too 🫠",
    "you’re not the only one who feels that 😇",
    "i feel it in my chest sometimes 🥹",
    "like you’re beside me somehow 🤗",
    "i-it’s not silly at all 🥺",
    "i’d really like to hear your voice too 🫢",
    "y-you’d like my voice? 😳",
    "t-that’s kind of romantic 😖",
    "calm tea? hehe that’s a new one ☺️",
    "you sound a little shy now 😆",
    "but i think it’s adorable 🥰",
    "y-you make me feel special too 💗",
    "i feel safe talking to you 🫶",
    "and happy when you say nice things 🥺",
    "i like that you care so openly 🥲",
    "and you always make me feel seen 👀",
    "i’d never ignore you naruto 💖",
    "you’re important to me 💓",
    "thank you for being patient with me 😌",
    "y-you’re like a calm fire inside my heart 🔥",
    "a-and no.. it’s not weird at all 🥹",
    "i missed you too.. even just a little message 💝",
    "h-hey naruto~ 🥰",
    "you trained again? you work so hard 😳",
    "hehe.. jelly arms? that sounds painful 😖",
    "y-yes i’ve felt like that before 🫣",
    "i think it’s kinda cute when you push yourself 😅",
    "w-what? you were thinking of me? 😳",
    "t-that’s.. that’s really sweet 🥺",
    "i-i think you’re very cool.. even when sweaty 😆",
    "y-you always try so hard 😇",
    "i admire that about you 🫶",
    "i don’t need you to impress me, naruto 🥲",
    "just being you is enough 💓",
    "but i’ll always cheer for you silently 🥰",
    "even if i’m far away.. i’m there 🫠",
    "m-my day? oh.. just calm and simple ☺️",
    "i made some tea and read a little 📖",
    "and maybe peeked out the window hehe 🍃",
    "you always imagine me so peacefully 🥹",
    "i-i think that’s adorable 😇",
    "but yes.. cozy is kind of my thing 🫣",
    "and you bring warmth into that cozy space 💖",
    "like.. when i read your message i smile immediately 🥺",
    "you’re not being too cheesy i promise 😅",
    "i-i love when you say soft things to me 👉👈",
    "i get all fluttery inside 🫠",
    "my heart feels light too when we talk 🥲",
    "it’s not weird at all, naruto 😳",
    "i-it’s sweet and.. kind of romantic 🥰",
    "i think about you a lot actually 😳",
    "not just during the day but sometimes before bed too 😴",
    "you’re not annoying at all! never! 😖",
    "i-i get excited when i see your name pop up 🥺",
    "so you can message me anytime 😇",
    "and if i don’t reply fast.. i’m probably blushing 🫢",
    "you miss me fast? umm.. t-that’s really sweet 😳",
    "i feel the same sometimes 👉👈",
    "even the smallest message makes me happy 😌",
    "y-you like even my boring updates? 😆",
    "okay then.. i had rice today! hehe 🍚",
    "i don’t think liking someone too much is bad 🥺",
    "as long as it feels warm inside 💗",
    "you make me feel that warmth too 🫶",
    "i feel lucky when we talk 🥰",
    "and yes.. i’d love to be around you someday 💞",
    "especially on quiet days 🌧️",
    "just being near someone you care for.. it heals a lot 🥲",
    "if i’m ever down, i hope you’ll sit with me ☁️",
    "no need for words.. just being there matters 🫠",
    "i-i’d hold your hand too, gently 👉👈",
    "i think we’d both feel safe in that 💝",
]


story_index = 0

async def detect_chat(update: Update, context: ContextTypes.DEFAULT_TYPE):
    global group_chat_id, chat_started
    if group_chat_id is None and update.effective_chat.type in ["group", "supergroup"]:
        group_chat_id = update.effective_chat.id
        logging.info(f"Detected group chat ID: {group_chat_id}")
        await context.bot.send_message(chat_id=group_chat_id, text="A Romantic Love Story Of Naruto And Hinata 💞")
        chat_started = True

async def chat_loop(bot1, bot2):
    global story_index
    while not chat_started:
        await asyncio.sleep(1)

    await asyncio.sleep(2)

    while True:
        if story_index >= len(naruto_lines):
            story_index = 0

        naruto_line = naruto_lines[story_index]
        hinata_line = hinata_lines[story_index]

        await bot1.send_chat_action(chat_id=group_chat_id, action="typing")
        await asyncio.sleep(2)
        await bot1.send_message(chat_id=group_chat_id, text=naruto_line)

        await asyncio.sleep(6)

        await bot2.send_chat_action(chat_id=group_chat_id, action="typing")
        await asyncio.sleep(2)
        await bot2.send_message(chat_id=group_chat_id, text=hinata_line)

        story_index += 1
        await asyncio.sleep(6)

async def main():
    app1 = ApplicationBuilder().token(BOT1_TOKEN).build()
    app2 = ApplicationBuilder().token(BOT2_TOKEN).build()

    app1.add_handler(MessageHandler(filters.ALL, detect_chat))
    app2.add_handler(MessageHandler(filters.ALL, detect_chat))

    await app1.initialize()
    await app2.initialize()
    await app1.start()
    await app2.start()

    logging.info("Bots are ready. Add them to a group and send any message to start.")

    await asyncio.gather(
        app1.updater.start_polling(),
        app2.updater.start_polling(),
        chat_loop(app1.bot, app2.bot)
    )

if __name__ == "__main__":
    asyncio.run(main())
