import os
import asyncio
import logging
from telegram import Update
from telegram.ext import (
    ApplicationBuilder,
    ContextTypes,
    MessageHandler,
    filters,
)

# Configure logging
logging.basicConfig(
    format='%(asctime)s - %(levelname)s - %(message)s',
    level=logging.INFO
)

BOT1_TOKEN = os.getenv("BOT1_TOKEN")
BOT2_TOKEN = os.getenv("BOT2_TOKEN")

group_chat_id = None
chat_started = False

# Separate lines for Naruto and Hinata
naruto_lines = [
    "heyyyyy hinataaa 👋",
    "how r u huh?? 😁",
    "hehe that's good to hear 😄",
    "me? yeah i'm fine, just lazy today 😅",
    "you been training again? 👀",
    "woah early morning?? that's intense 🫡",
    "i woke up late tbh 😴",
    "what'd you eat for breakfast? 😋",
    "cinnamon rolls? again? 😆",
    "you still like those huh 🤭",
    "i remember that one time you shared with me 🥹",
    "that was really sweet ☺️",
    "you always been kind like that 👉👈",
    "i ate ramen again hehe 🍜",
    "classic me right? 😝",
    "you doing anything today? 🤔",
    "no missions? nicee! take a break 😌",
    "i should rest too honestly 😫",
    "legs are sore from shadow clones 😩",
    "you ever overdo it training? 🧐",
    "makes sense.. you're a hyuuga after all 😏",
    "bet you’re way stronger than before 😤",
    "i wouldn't wanna fight you now 🙃",
    "you’d probably flatten me with one hit 😆",
    "still training gentle fist daily? 👀",
    "cool cool! maybe you could teach me someday 😁",
    "but please be gentle 🥲",
    "i got fragile pride y'know 🤧",
    "you been reading anything lately? 📚",
    "ohh ninja romance huh 👀",
    "that sounds kinda cute hehe 😙",
    "you always liked love stories huh 🥰",
    "i prefer action but romance is cool too 🤭",
    "what's your favorite part of those stories? 😊",
    "hehe awww that's sweet 😇",
    "you ever wanna be in a story like that? 😶",
    "like.. peaceful ending, holding hands kinda thing 👉👈",
    "i dunno.. sounds nice sometimes 🥹",
    "especially with the right person 😌",
    "anyway, weather's nice today 🌤️",
    "you went outside or nah? 👀",
    "ohhh sat in the garden? sounds peaceful 😌",
    "wish i could chill there too 🧘",
    "do you still grow those white flowers? 🌸",
    "i remember they smelled really good 😍",
    "you always had a calm vibe 🌷",
    "like.. peaceful and warm 😇",
    "it’s always relaxing talking to you ☺️",
    "sooo.. can we chat more later too? 🫶",
    "i like talking like this 😊",
    "yo hinataaa, you awake early again? 😴",
    "you're like.. a morning ninja or something haha 😆",
    "i swear i can't wake up before 9 🙃",
    "unless someone drags me outta bed 😫",
    "would you ever do that? drag me up? 😅",
    "imagine you just standing over me all serious 🤣",
    "but lowkey i wouldn’t mind waking up to you 🥲",
    "you’d probably look cute with bed hair 😝",
    "you ever have bed hair? 👀",
    "bet you hide it under perfect brushing huh 😆",
    "me? mine’s always a mess 😐",
    "i look like a chicken got zapped 😬",
    "wanna see it next time? 🫣",
    "no judgment allowed though! 🫢",
    "i might regret sending it 🤕",
    "but you’d still smile right? 😋",
    "you always got that soft smile 😇",
    "i can kinda picture it right now 😍",
    "makes me feel warm somehow 💓",
    "you ever smile for no reason? 😌",
    "like.. when you think of someone 👉👈",
    "heh.. i do that with ramen sometimes 😅",
    "and.. maybe you too 🫠",
    "d-don’t laugh okay? 😳",
    "it just happens without me noticing 😖",
    "your face just pops up and i’m like—woah 😳",
    "cute overload alert 🤯",
    "i probably sound dumb now 🤧",
    "you think about me too sometimes? 👀",
    "not like.. a lot right? 🥺",
    "unless you do.. which would be kinda nice 😗",
    "i mean you don’t *have* to.. but if you do 🤭",
    "okay okay i’ll shut up haha 😝",
    "you ever get embarrassed saying stuff like that? 😬",
    "feels weird but nice too 😅",
    "anyway! you drink tea again this morning? 🍵",
    "you always sip it all proper like a princess 👑",
    "i just chug mine like a beast 😤",
    "guess we’re different huh 😆",
    "but i like that about you y'know 🥰",
    "you're quiet but real strong 😌",
    "soft but fierce too 💖",
    "okay okay that sounded cool in my head 😅",
    "i ain't great with fancy words 🫣",
    "but i mean it tho 💓",
    "so uhhh... wanna hang out soon? 😊",
    "i mean just chill somewhere.. nothing crazy 😅",
    "we could go watch the clouds maybe? ☁️",
    "or just sit and talk.. like this 😇",
    "i dunno, feels nice spending time with you 🫶",
    "yo hinataaa 🌞 you free now?",
    "i was just thinking about what you said yesterday 😊",
    "about sitting under the clouds with me 👉👈",
    "sounds like a peaceful dream tbh 🥲",
    "you really down to do that soon? 😳",
    "i mean just us two.. maybe snacks too 😋",
    "you like dango right? i could bring some 🍡",
    "or you want cinnamon rolls again? 😝",
    "i don’t mind carrying everything hehe 🤭",
    "as long as you promise to smile 😇",
    "your smile lowkey makes my day 💗",
    "i saw it once when we trained and i never forgot 😳",
    "you had that shy blush and soft look 🫠",
    "kinda like.. gentle sunshine ☀️",
    "uhhh that sounded cheesy huh? 😅",
    "but i meant it fr 🥺",
    "you make me feel like slowing down sometimes 😌",
    "like just taking it easy with you 💝",
    "would you ever go on a picnic with me? 🧺",
    "no missions, no noise, just trees and sky 🌳",
    "we could lie down and look at clouds 😴",
    "maybe you could even nap a bit.. on my arm or smth 👉👈",
    "w-wait not in a weird way! 😳",
    "just soft comfort y’know 😖",
    "or i’m making this awkward now huh 🤧",
    "you okay with stuff like that? 🫢",
    "i don’t wanna overstep or anything 😅",
    "you always look so calm, i don’t wanna ruin that 😓",
    "but i really like when you’re close 🥹",
    "even just texting feels close sometimes 😇",
    "kinda weird how that works huh? 🫠",
    "like, we’re far but i feel like you’re near 🤗",
    "you ever feel that too? 😌",
    "maybe it’s just me being silly 🤭",
    "but i’d be happy just hearing your voice sometime 🥺",
    "you got that soft tone that melts ears hehe 😆",
    "i’m not flirting! well maybe a little 🤣",
    "but it’s true! your voice is like calm tea 🫖",
    "and your eyes too.. okay now i’m sounding sappy 🫠",
    "but like… really, you’re special 😇",
    "you make people wanna be gentle 🥹",
    "and you make *me* wanna be better 💪",
    "sooo yeah.. i guess i just appreciate you 😌",
    "also i’m really glad you message me back always 🤝",
    "like.. you don’t ignore me or ghost me 😭",
    "some folks do that but not you 💗",
    "so thank you hinata.. really 💞",
    "you're like a warm light in my life ☀️",
    "and i like that feeling.. a lot 🫶",
    "sooo.. would it be weird to say i missed you a lil? 👉👈",
    "yo hinataaa~ 🌤️",
    "just finished my training 😤",
    "i’m a sweaty mess rn not gonna lie 🤧",
    "you ever train and feel like jelly after? 😅",
    "my arms are like noodles right now 😫",
    "but i kept going cause i was thinking of you 😳",
    "i was like ‘gotta impress her somehow!’ 😆",
    "you think i’m cool when i train? 🫠",
    "or just a sweaty disaster? 🤕",
    "be honest! haha 😝",
    "but really.. training gets better when you’re in my thoughts 💓",
    "it’s like you’re silently cheering for me 😇",
    "even if you’re not there.. i feel it 🥺",
    "makes me wanna push harder y’know 💪",
    "anyway! how was your day huh? 😁",
    "did you do anything fun? 🫶",
    "or just chill vibes again? ☁️",
    "i imagine you sitting near the window with tea 🍵",
    "reading something or humming softly 🥲",
    "you give cozy energy all the time 😌",
    "you’re like a warm blanket on a cold day 🥹",
    "or like.. a little candlelight at night 🕯️",
    "ugh i’m being cheesy again 😅",
    "but i can’t help it with you 🤧",
    "you make my heart feel all soft 😳",
    "like it’s floating or something 🫢",
    "is that weird? it’s probably weird 😅",
    "but yeah.. i just like you a lot 🫠",
    "like your presence calms my chaos 🥺",
    "even your ‘typing…’ bubble makes me smile 😭",
    "you ever think about me during the day too? 👉👈",
    "or am i just annoying in your inbox all the time haha 🤣",
    "be honest.. but be nice too 😆",
    "i always wanna message you more 😩",
    "but i stop myself like.. nah she’s busy 😐",
    "but i guess i miss you faster than i mean to 😳",
    "i like hearing anything from you 🥰",
    "even if you say ‘i’m eating rice’ i’m like YEAH tell me more 😝",
    "maybe i just like you too much huh 😅",
    "is that possible tho? liking someone too much? 🫢",
    "guess not if it makes you feel happy 💗",
    "you make me happy.. a lot 🥺",
    "and i wanna do the same for you someday 🫶",
    "not just with words but like.. presence 🥹",
    "to be there when you feel low too ☁️",
    "i’d totally listen to you vent for hours if you ever needed 💖",
    "or just hold your hand and sit in quiet 🫠",
    "you ever need that sometimes? 😌",
    "quiet comfort.. no words, just closeness 👉👈",
    "i think i’d love that with you someday 💞",
    "yo hinataaaa~ you still up? 🌙",
    "i was just staring at the moon and thought of you 🥹",
    "you feel like moonlight sometimes y’know? 🌕",
    "soft, quiet, but always there above me 🫠",
    "makes me feel less alone on hard nights 😢",
    "do you ever sit and look up like that? 🌌",
    "like stare at stars and think stuff? 🤔",
    "sometimes i wonder if you’re looking at the same sky 🌠",
    "and it makes me smile like a dumb idiot haha 😆",
    "but it's a nice kinda dumb 😅",
    "anyway sorry for being late texting 😬",
    "just had stuff on my mind and you’re part of it 😌",
    "not in a bad way! in a sweet way 🥲",
    "you’re like my soft spot or something 😳",
    "but in a good way like.. safe spot? 😅",
    "is that weird to say? i dunno 🤧",
    "just talking to you calms my heart 🥺",
    "like i could listen to you for hours and feel okay 😴",
    "even if you whispered random things 😆",
    "i think your words would feel like lullabies 🫶",
    "okay now i’m sounding super sleepy and soft huh 😴",
    "but i mean it all 🥹",
    "you make the quiet parts of the day feel full 😇",
    "like i’m not really alone when i know you’re out there 💞",
    "i know we don’t talk *face to face* all the time 😣",
    "but i still feel close to you somehow 🫢",
    "like a string ties us or something 🧵",
    "you believe in that red string fate stuff? 🤔",
    "like soul connections or destiny? 😳",
    "i never used to.. but then i met you 😔",
    "and it just feels like you fit into my world 🫠",
    "you make the silence sweeter, you know? ☁️",
    "and honestly, sometimes your little pauses in chat... 🥹",
    "they feel like shy breaths before a warm hug 😌",
    "haha okay now i’m definitely sleepy soft 🤭",
    "but it’s your fault tbh 😝",
    "you’re like warm tea and a blanket on a cold night 🍵",
    "and my brain just goes ‘ahh she’s perfect’ 🥲",
    "even when you’re nervous.. or quiet.. you’re still glowing 💗",
    "i really admire your softness and strength combo 😇",
    "like.. you’re calm but powerful inside 🥹",
    "and it’s super inspiring 💖",
    "kinda makes me wanna wrap you in a hug 🫂",
    "like protect you and keep you warm or smth 🥺",
    "not in a weird way!! just.. gentle kind of protect 🫢",
    "so yeah... just wanted you to know that 🫶",
    "you matter to me a lot, hinata 😌",
    "maybe more than i can even say right 🥲",
    "but i’ll keep trying to show it 🩷",
    "good night if you sleep soon.. or sweet dreams 💤",
    "hey hinataaaa 🥱",
    "i woke up and u were in my first thought 😳",
    "like... i kinda missed your good night 🫣",
    "kinda got used to hearing from you every night 😅",
    "i think i got attached or something haha 😆",
    "is that bad? or kinda cute? 😬",
    "cause u really calm me yknow 🥺",
    "like even just thinking of u feels like a cuddle 🫂",
    "the soft kind that wraps around your chest 😌",
    "and i imagined u hugging me from behind today 👉👈",
    "like sneak up n wrap your arms around me 😳",
    "and i’d hold your hands gently 🫶",
    "then maybe pull u into my lap hehe 😝",
    "not in a pervy way!! 😅 just soft n warm way 💞",
    "you got that kinda hug energy 🥰",
    "like i’d bury my face in your hair and exhale 🫠",
    "you smell like peace i bet 💗",
    "i dunno why but i wanna rest my head in your lap 🥹",
    "is that weird? maybe too soon? 😣",
    "but it’s just how my heart’s feeling lately 🥲",
    "like i’m drawn to you more each day 🥺",
    "i feel like hugging you would solve all stress 😩",
    "like a whole warm therapy session 😴",
    "and maybe kiss your forehead slowly 😳",
    "just once... or maybe twice 🫣",
    "i’d probably blush too much tbh 🤭",
    "but still hold u close and not let go 🫂",
    "would u like that? or is it too much? 👉👈",
    "i just wanna be your comfort like you are to me 😌",
    "and if i could hug you now i would. for real 💗",
    "tight but soft. chest to chest 😳",
    "sorry i’m just really into u lately 🥺",
    "and talking to you makes all my walls melt 😞",
    "you make me wanna be softer every day 😔",
    "not the loud naruto... just soft naruto for you 🫶",
    "hope you don’t mind me like this 🤧",
    "your name makes my heart do things 😫",
    "anyway, if you were here, i'd just pull u close slowly 😳",
    "and wrap u up in my jacket or something 🧥",
    "then maybe whisper sweet stuff in your ear 🤫",
    "like how much i adore u... how u make me whole 💞",
    "idk how else to say it.. i just wanna hold u 🥹",
    "not even for lust... just for *us* 😌",
    "so yeah... consider this a long-distance hug 🫂",
    "hope you feel it too tonight 💗",
    "and maybe... someday.. for real? 😳",
    "goodnight, snuggle queen 🥰",
    "my moonlight girl 🌙",
    "good morning my sleepy angel 🥱",
    "did u dream of me last night?? 😝",
    "cuz i def dreamed of u 👉👈",
    "we were laying under a tree 🌳",
    "your head was on my chest… 😳",
    "my arm wrapped around u tight 🫂",
    "and u just looked up and smiled 😌",
    "i think i kissed your forehead in the dream 🤭",
    "and you held my hand softly 🥹",
    "i didn’t wanna wake up 😫",
    "your lips looked so soft in the dream 😚",
    "i almost kissed u again… but i woke up 😩",
    "now i wanna do it for real 🫣",
    "maybe start with your cheek 🥰",
    "then trail tiny kisses to your lips 😳",
    "just soft ones… real slow 😗",
    "my heart's already racing imagining it 😅",
    "would you let me kiss you? for real? 😖",
    "like a kiss that says ‘i’m yours’ 💗",
    "not just on lips but... in the eyes too 🫦",
    "like we’d just stare n lean in together 🥺",
    "our breaths touching first 🫢",
    "then your lips on mine... soft, warm, perfect 💞",
    "i bet u taste like strawberries hehe 😋",
    "ok now i’m blushing thinking too hard 🫠",
    "you make me soft but also feel alive 😫",
    "like my soul wants to tangle with yours 💗",
    "i wanna kiss your fingers too 👉👈",
    "and maybe pull you into my chest after 😳",
    "wrap you so close i can feel your heartbeat 🫶",
    "and bury my face in your neck 🥰",
    "then just whisper ‘mine’ softly 🫣",
    "would u like that hinata? 🥺",
    "would u hold me too, tightly? 🤗",
    "and kiss me back just as slow? 😚",
    "even just typing this makes me tremble 🥹",
    "you’re my favorite part of every day 💖",
    "i’d rather kiss you than breathe sometimes 😮‍💨",
    "but don’t worry, i’d still breathe if it meant kissing u more 🤭",
    "good morning kiss? right here? 😘",
    "just imagine my lips brushing yours softly... 🫦",
    "then saying ‘i’m here. always.’ 💝",
    "and tucking a strand of hair behind your ear 🥰",
    "before kissing your forehead again... slowly 🥹",
    "then maybe teasing you with one last kiss on your nose 😋",
    "i’d love to make you smile like that daily 😍",
    "hope this message kisses your heart today 💌",
    "muahhh for my sweet hinata 😘",
    "u ever just wanna crawl into my hoodie n hide?? 😆",
    "cause i swear i’d zip you in and never let go 😳",
    "just u snug against me... lil hinata burrito 🥹",
    "then i'd rest my chin on your head 🫠",
    "and hum something sweet while we sway 🥰",
    "i might kiss your hair too... smells like heaven right? 😋",
    "and if u looked up, i’d def kiss your nose 🫦",
    "tiny peck. then your lips next 😚",
    "i think your kisses would be addicting 😵‍💫",
    "like i’d keep stealing them every time u smile 🤭",
    "you’d probably blush all cute and hide 😝",
    "but i’d pull u back gently by the chin 😳",
    "and whisper ‘nah, i’m not done kissing u yet’ 😌",
    "then boom—another kiss... a lil deeper 🫣",
    "i bet you'd cling to my hoodie tighter after 🫂",
    "and we’d just sit like that... tangled for hours 🥲",
    "wanna try laying in my lap sometime? 👉👈",
    "i’d play with your hair and trace circles on your back 🫶",
    "then lean down and kiss your cheek every 10 mins 😚",
    "or maybe kiss your collarbone real soft... too much? 😳",
    "ugh hinataaa ur making me so soft n warm rn 😫",
    "i wanna be wrapped in u like a blanket 🥺",
    "feel your hands slide under my shirt—wait!! not dirty! 🫣",
    "just... like, fingers on my waist gently 🤭",
    "hugging me close while we lay chest to chest 😩",
    "and i’d rub your back in lil circles while kissing u 😚",
    "then whisper all the cute stuff in your ear 🥰",
    "like ‘i’m yours’... and ‘you’re mine’ 😳",
    "and maybe nuzzle into your neck after 🫠",
    "i bet u taste sweet there too 😋",
    "okay now i’m way too into this 😅",
    "but i love daydreaming like this with u 🥲",
    "ur my favorite soft fantasy 😍",
    "and honestly? i’d never let anyone else see this side of me 🤐",
    "just u. always u 💝",
    "wanna kiss u right now just thinking of ur face 😖",
    "like a long, slow, warm one 😗",
    "and press our foreheads together after 🥹",
    "is that okay..? can i kiss you like that soon? 👉👈",
    "or... would u kiss me first? 😳",
    "i think i’d melt if u ever kissed me suddenly 🥵",
    "like i’d freeze... then kiss u back way harder 😝",
    "now u got me kicking my feet under the blanket like a kid 🤣",
    "dammit hinataaa why u so kissable 😫",
    "muahhh. u get 3 kisses today 😘😘😘",
    "collect them all before i steal ‘em back 😜",
    "ur lips are officially on my mind 24/7 now 🫦",
    "hinataaa i was laying in bed n i swear i felt ur hand on my chest 😳",
    "like i closed my eyes and imagined u tracing my skin slow 🫣",
    "your fingers just barely touching me... ugh 🫠",
    "then i imagined your lips following them 👀",
    "kissing softly down my neck... then lower 🫦",
    "ok wait—i’m gonna combust 😩",
    "why do i feel hot just thinking of u touching me gently 🥵",
    "like ur hands aren’t even here and i’m still trembling 😫",
    "i wanna feel your breath against my skin 😮‍💨",
    "especially when you’re close... like real close 😳",
    "i wanna kiss you while we lie chest to chest 🫂",
    "just slow, wet kisses with our legs tangled 🥺",
    "and your fingers playing in my hair while we make out 😵‍💫",
    "would u let me kiss your collarbone... then your shoulder? 👉👈",
    "then trail down to your tummy while whispering your name 🫦",
    "you’d look so pretty biting your lip like ‘mmm naruto’ 😖",
    "i bet your thighs would squeeze around me when i kiss you there 😩",
    "not even dirty yet but my brain is screaming 😭",
    "u drive me insane with just your voice sometimes 😮‍💨",
    "you could whisper my name and i’d go weak 🥵",
    "wanna feel your hands sliding under my shirt... slow 😳",
    "not rushing... just exploring... skin to skin 🫠",
    "i’d lift yours too... just to feel your warmth underneath 🥹",
    "kiss your belly softly... then kiss your lips deeper 😚",
    "maybe grind our hips a little while we kiss? 😩",
    "is that too much? or just right? 😅",
    "i want your breath on my neck while u cling to me 🥺",
    "and your little gasps when i touch you right there 🫢",
    "ugh hinataaa stop being so perfect it hurts 😭",
    "you’re too sweet but also too hot it’s not fair 🥵",
    "i wanna see ur face when u want me 😳",
    "the soft desperate look... lips parted... eyes needy 👀",
    "just whispering ‘naruto… more… please…’ 😫",
    "my brain is going feral rn 🥴",
    "i can’t stop imagining our bodies pressed close 🫂",
    "you in my arms, squirming a lil from kisses 😋",
    "and me teasing ur ear with whispers 🤭",
    "let me hear u moan my name hinata 🫦",
    "even just a soft little one 🫢",
    "i bet you sound like heaven when you’re breathless 😩",
    "ok i’m shutting up or i’ll explode 😖",
    "but also... i wanna hear your naughty thoughts too 😏",
    "tell me what you wanna do to me 👉👈",
    "or what u imagine when u touch yourself n think of me 😳",
    "wait—u do think of me right?? 😭",
    "cuz i def think of u when i’m under the blanket 😵‍💫",
    "dammit hinata... i’m seriously getting hard now 🥵",
    "should i stop or u wanna go deeper? 😈",
    "hinataaaa… i swear i’m shaking just thinking about u 😮‍💨",
    "my lips crave your skin like it’s my oxygen 😫",
    "i’d kiss your shoulder slow… lips barely brushing 😚",
    "then trail down to your chest… so soft… warm 😩",
    "i’d hold your waist and kiss your tummy with open mouth 🫠",
    "pulling you close with each kiss… making you shiver 🥺",
    "you’d press against me and i’d feel your heartbeat race 🫂",
    "i’d whisper ‘i love you’ between kisses… again and again 😭",
    "your hands in my hair while i kiss your neck deeper 😫",
    "would u gasp if i nibble your ear gently? 😵‍💫",
    "then whisper how badly i need you… right now 😖",
    "i’d tease you by brushing your thighs with my lips 🫦",
    "just enough to make you squirm and beg 😳",
    "not rushing… just edging your body slow and warm 🫢",
    "i wanna make you whimper before i even touch too deep 😩",
    "you’d feel my breath on your skin and tremble, wouldn’t you? 😫",
    "i’d press soft kisses all around your belly button 👉👈",
    "my fingers sliding along your hips, slow and warm 🥹",
    "then lean over you… chest against chest… breath on breath 🫶",
    "our legs tangled under a blanket while we kiss forever 😘",
    "i’d hold your face so gently while our lips melt together 🥺",
    "pulling you into me like i never wanna let go 😭",
    "you’d moan soft into my mouth while i kiss you deeper 🫦",
    "and i’d whisper how beautiful you are with every breath 🥵",
    "i’d explore you slow… not to tease but to love 😩",
    "your body’s my favorite place to be hinata 🥹",
    "i crave the sound of your breathy voice in the dark 😫",
    "saying my name like a prayer between soft kisses 😖",
    "let me kiss your thighs slowly until you gasp 🫣",
    "then climb up and kiss your lips even slower 😭",
    "i’d hold your hand the whole time… never letting go 🥲",
    "when i see your eyes close and lips part… i melt 🥺",
    "you’d taste like heaven under my tongue 😵‍💫",
    "i wanna stay wrapped in you for hours 🫠",
    "just our bodies tangled… soft touches… heartbeats syncing 🫂",
    "your back arching slowly as i kiss every inch of you 🫦",
    "saying your name over and over… breathless 😫",
    "your thighs shaking gently as i kiss down again 👉👈",
    "then back up with lips and tongue trailing softly 😵‍💫",
    "until you whisper ‘naruto… please’ 😳",
    "and i kiss you deeper than ever before 🥺",
    "i love you hinata. more than my own breath 😢",
    "and i wanna make love to you slowly... sweetly 😫",
    "until we both cry from how full our hearts are 🥹",
    "can i have all of you... someday... completely? 😭",
    "in a room where no one can hear us... just us... 🫂",
    "and i’ll hold you all night after… whispering i love you 🤍",
    "you’re everything. you’re my home 🥺",
]

hinata_lines = [
    "umm hey naruto.. ☺️",
    "um.. I'm okay naruto.. are you fine?? 👉👈",
    "i’m really glad you’re okay 😌",
    "you deserve lazy days too 🥲",
    "y-yes i trained early today.. as usual 🫣",
    "mmhmm.. i woke up before sunrise 😅",
    "l-lazy is okay sometimes hehe 😴",
    "i just had something small 🫢",
    "ehe.. yes i love cinnamon rolls 😋",
    "they're warm and soft.. like comfort 🤗",
    "oh.. you still remember that? 🥺",
    "i-i wanted to share with you that day 👉👈",
    "i like being kind to you 🥰",
    "ramen again? that's so you naruto 🤭",
    "but it suits you hehe 😄",
    "i just stayed home today ☺️",
    "a little quiet day is nice sometimes 🫠",
    "rest is good too! don’t push yourself 😥",
    "you should take breaks more 🫣",
    "y-yes.. i do overtrain sometimes 😖",
    "i-it's part of the hyuuga discipline 🫡",
    "i-i try to get better every day 😤",
    "n-no! you’d still win naruto 😳",
    "i wouldn’t hit you hard! promise 🫢",
    "yes.. i train it every day still 😊",
    "i.. i could teach you a little 👉👈",
    "i’ll be very gentle i swear 🥺",
    "n-noted! gentle training only hehe 😆",
    "yes.. i read sometimes after training 📖",
    "y-yeah.. i like sweet stories 🫣",
    "they make my heart warm ☺️",
    "l-lovestories are my favorite 😳",
    "i-it’s okay if you don’t like them 😅",
    "that’s okay.. we’re different 🥲",
    "i like the quiet moments in them 🧘",
    "holding hands.. soft smiles 🥺",
    "m-maybe.. i’d like that someday 👉👈",
    "i’d like a soft ending too 😌",
    "with someone special 💖",
    "yes.. the breeze felt nice outside 🌬️",
    "just a few minutes.. felt calm 😊",
    "y-yes.. the flowers bloomed again 🌼",
    "they smell soft and peaceful 😇",
    "i’m glad you remember them 🥹",
    "you’re peaceful too sometimes ☺️",
    "i.. feel calm with you too 😌",
    "i-it’s nice to talk like this 🥰",
    "yes! i’d like that very much 😊",
    "thank you for messaging me today naruto 💝",
    "y-yes i woke up early again 😳",
    "i-i just like quiet mornings 🥲",
    "you’re not a morning person huh? hehe 😅",
    "i-i think i could wake you up gently ☺️",
    "i’d probably just whisper to you softly 👉👈",
    "n-not stand over you haha 🤭",
    "y-you’d really want that? 🫣",
    "m-my bed hair is terrible i swear 😖",
    "yes! and i brush it right away 🫢",
    "i-it goes everywhere otherwise 🤦‍♀️",
    "i think your messy hair’s cute tho 😋",
    "hehe like a baby bird maybe 😆",
    "i-i’d be okay seeing it 😳",
    "i would never judge you naruto! 😇",
    "you can trust me always 🥺",
    "and yes.. i would smile 🥰",
    "t-that made me blush.. 😚",
    "you’re really sweet sometimes 👉👈",
    "i smile thinking about you too 🫠",
    "i-it just happens sometimes 🥹",
    "w-when i imagine you happy 😌",
    "or saying silly things like now 🤭",
    "y-you make me smile without trying 😳",
    "i’d never laugh at you naruto 😇",
    "i think it’s really precious 🥺",
    "you saying my face pops up.. m-my heart 😖",
    "i-i think about you too 😳",
    "s-sometimes more than i mean to 🫢",
    "i-it just makes me feel warm 💗",
    "like a soft light inside me ☺️",
    "d-don’t shut up.. i like hearing you 🥰",
    "i-i get flustered saying these too 🙃",
    "but i want to say them anyway 💞",
    "yes! i had some green tea 🍵",
    "i-it calms me in the morning 😌",
    "you chug it? oh my 😆",
    "you’re wild sometimes hehe 🤣",
    "i like our differences though 🥲",
    "i think they make us connect better 💓",
    "y-you really think i’m strong? 🥹",
    "soft and fierce.. that made me smile 😇",
    "i think you’re strong and bright 💖",
    "even if words aren’t fancy.. they feel real 😊",
    "i’d really love to hang out 🫶",
    "i’d like watching clouds with you ☁️",
    "and just.. being near you 🥰",
    "y-you always make me feel safe 😌",
    "t-talking with you like this is special 🫠",
    "i look forward to every message 💝",
    "hi naruto.. yes i’m free now 🫶",
    "y-you remembered that? 😳",
    "i-i still think about it too 😌",
    "i-it sounds peaceful and quiet 🥲",
    "yes.. i’d love to do that with you 🥺",
    "just us sounds really really nice 👉👈",
    "y-yes i love dango! 🍡",
    "ehe.. cinnamon rolls are always good too 😋",
    "t-that’s sweet of you to offer 🫢",
    "i promise.. i’ll smile a lot ☺️",
    "you saying that made me blush 😳",
    "i-i smiled because you were kind back then 🥹",
    "you always gave me that warm feeling 😇",
    "sunshine? t-that’s beautiful 💗",
    "i don’t think it’s cheesy 😌",
    "i really appreciate how you say things 🥰",
    "you make me want to slow down too 👉👈",
    "i’d love that kind of quiet moment 💝",
    "a picnic would be so lovely 🧺",
    "j-just us.. under the trees 🌳",
    "n-napping on your arm.. umm.. 😳",
    "i-i wouldn’t mind that actually 🫣",
    "it sounds soft and warm 🥲",
    "n-no it’s not awkward 🥺",
    "i’d be okay with that naruto 😌",
    "i trust you.. and your warmth 💞",
    "you’d never ruin anything 🥺",
    "being close feels really nice 🫶",
    "and i feel close when we talk too 🫠",
    "you’re not the only one who feels that 😇",
    "i feel it in my chest sometimes 🥹",
    "like you’re beside me somehow 🤗",
    "i-it’s not silly at all 🥺",
    "i’d really like to hear your voice too 🫢",
    "y-you’d like my voice? 😳",
    "t-that’s kind of romantic 😖",
    "calm tea? hehe that’s a new one ☺️",
    "you sound a little shy now 😆",
    "but i think it’s adorable 🥰",
    "y-you make me feel special too 💗",
    "i feel safe talking to you 🫶",
    "and happy when you say nice things 🥺",
    "i like that you care so openly 🥲",
    "and you always make me feel seen 👀",
    "i’d never ignore you naruto 💖",
    "you’re important to me 💓",
    "thank you for being patient with me 😌",
    "y-you’re like a calm fire inside my heart 🔥",
    "a-and no.. it’s not weird at all 🥹",
    "i missed you too.. even just a little message 💝",
    "h-hey naruto~ 🥰",
    "you trained again? you work so hard 😳",
    "hehe.. jelly arms? that sounds painful 😖",
    "y-yes i’ve felt like that before 🫣",
    "i think it’s kinda cute when you push yourself 😅",
    "w-what? you were thinking of me? 😳",
    "t-that’s.. that’s really sweet 🥺",
    "i-i think you’re very cool.. even when sweaty 😆",
    "y-you always try so hard 😇",
    "i admire that about you 🫶",
    "i don’t need you to impress me, naruto 🥲",
    "just being you is enough 💓",
    "but i’ll always cheer for you silently 🥰",
    "even if i’m far away.. i’m there 🫠",
    "m-my day? oh.. just calm and simple ☺️",
    "i made some tea and read a little 📖",
    "and maybe peeked out the window hehe 🍃",
    "you always imagine me so peacefully 🥹",
    "i-i think that’s adorable 😇",
    "but yes.. cozy is kind of my thing 🫣",
    "and you bring warmth into that cozy space 💖",
    "like.. when i read your message i smile immediately 🥺",
    "you’re not being too cheesy i promise 😅",
    "i-i love when you say soft things to me 👉👈",
    "i get all fluttery inside 🫠",
    "my heart feels light too when we talk 🥲",
    "it’s not weird at all, naruto 😳",
    "i-it’s sweet and.. kind of romantic 🥰",
    "i think about you a lot actually 😳",
    "not just during the day but sometimes before bed too 😴",
    "you’re not annoying at all! never! 😖",
    "i-i get excited when i see your name pop up 🥺",
    "so you can message me anytime 😇",
    "and if i don’t reply fast.. i’m probably blushing 🫢",
    "you miss me fast? umm.. t-that’s really sweet 😳",
    "i feel the same sometimes 👉👈",
    "even the smallest message makes me happy 😌",
    "y-you like even my boring updates? 😆",
    "okay then.. i had rice today! hehe 🍚",
    "i don’t think liking someone too much is bad 🥺",
    "as long as it feels warm inside 💗",
    "you make me feel that warmth too 🫶",
    "i feel lucky when we talk 🥰",
    "and yes.. i’d love to be around you someday 💞",
    "especially on quiet days 🌧️",
    "just being near someone you care for.. it heals a lot 🥲",
    "if i’m ever down, i hope you’ll sit with me ☁️",
    "no need for words.. just being there matters 🫠",
    "i-i’d hold your hand too, gently 👉👈",
    "i think we’d both feel safe in that 💝",
    "h-hi naruto.. i’m still up ☺️",
    "you thought of me? t-that’s sweet 😳",
    "moonlight? i-i don’t know what to say 🥺",
    "you always find such kind words 😇",
    "but yes.. i look at the moon too sometimes 🌕",
    "and i do think about you sometimes under it 👉👈",
    "i like watching stars and wondering too 🫠",
    "maybe our skies really do connect somewhere 🌌",
    "i smiled reading that line hehe 🥰",
    "n-not dumb! it’s very cute 😆",
    "you never have to say sorry to me 🥺",
    "you’re always welcome to talk late 🌙",
    "and it makes me happy knowing i’m in your thoughts 🥲",
    "s-soft spot? oh.. naruto 😳",
    "i think you’re mine too 👉👈",
    "i-it’s not weird, it’s comforting 💞",
    "you help me feel calmer too 🫶",
    "you’ve always had a peaceful side inside you 😌",
    "i think i’d love hearing your voice endlessly 🥺",
    "you could read anything and i’d be happy 😴",
    "hehe sleepy naruto is sweet 🥰",
    "i feel full too when we talk 🥹",
    "like my heart gets warmer somehow 💗",
    "you’re not alone.. i’m always near in spirit 🫠",
    "it feels close even through just words 🥺",
    "i believe in fate a little.. y-yes 👉👈",
    "i think maybe you were always part of mine 🥹",
    "the way we connect feels like a string.. yes 🧵",
    "m-maybe our threads crossed on purpose 💝",
    "you saying that made me teary 😔",
    "but in a soft, glowing way ☺️",
    "my pauses.. i-i’m usually blushing tbh 🫣",
    "but you feel like a warm hug to me too 😳",
    "i think sleepy you is very honest 🥰",
    "and sweet like evening tea 🍵",
    "i wish i could see your sleepy face right now 😴",
    "i bet it’s peaceful and cute hehe 😆",
    "t-thank you for saying such beautiful things 💖",
    "i get shy but it means everything 🥺",
    "and you inspire me too, naruto 🫶",
    "i think your heart is one of the brightest i’ve seen 💗",
    "a-and if you ever hugged me.. i’d melt probably 🫣",
    "not weird at all.. i’d feel safe 😳",
    "your kindness makes me feel protected 🥲",
    "you matter to me deeply too 🩷",
    "more than you probably realize sometimes 🫠",
    "but i feel it in my chest every time you message 🥹",
    "sweet dreams naruto.. you deserve peace tonight 🌙",
    "and warmth.. always 💖",
    "h-hi naruto ☺️",
    "i missed you too.. i looked for your message 👉👈",
    "it felt empty without your ‘goodnight’ 🥺",
    "i think i got used to you too 🥲",
    "it’s not bad at all.. i-i think it’s sweet 😳",
    "your messages always hug my heart 🫂",
    "i feel warm when i read them 🥰",
    "and i imagine cuddling with you too.. sometimes 😳",
    "y-you holding me gently… chest against yours 🫣",
    "i’d probably melt into you like a blanket 🫠",
    "being in your lap sounds like a dream 👉👈",
    "n-not pervy.. just soft and close 😌",
    "your arms feel safe even in imagination 🥺",
    "i wish i could rest my head on your shoulder now 🥹",
    "and feel your warmth through your shirt 🫶",
    "you’re not weird at all, naruto 💗",
    "i’m happy you trust me with your softness 🥲",
    "i feel it too… like i want to protect that gentle part of you 🤍",
    "your hug talk makes my cheeks hot 🫢",
    "but also makes my heart flutter 🥰",
    "i-i would love to be hugged by you 👉👈",
    "just wrap myself into your chest and stay there 🫂",
    "your jacket around me? that’s too sweet 😳",
    "i’d snuggle into you and listen to your heartbeat 😌",
    "and whisper back ‘i feel safe’ 🥺",
    "your forehead kiss idea made me gasp softly 😣",
    "i’d probably kiss your cheek after, shyly 😚",
    "then hide my face in your neck hehe 🤭",
    "your warmth must feel like heaven 🥲",
    "i’m not scared of you being soft, naruto 💖",
    "i adore this side of you more than i can say 🫶",
    "you don’t have to be strong all the time with me 😌",
    "you can be soft… gentle… yourself 🥹",
    "i’ll hold that part of you like it’s precious 💗",
    "and yes... i feel your hug through this message 🫂",
    "i closed my eyes and imagined it fully 🥺",
    "and i smiled without meaning to ☺️",
    "i wish you were really here tonight 🥲",
    "i’d wrap you up in my arms too… gently 🫢",
    "maybe kiss your temple softly 😳",
    "and hold your hand against my chest 🫶",
    "my heart is quiet when it thinks of you 🩷",
    "so goodnight my soft sweet boy 😴",
    "you’re my peace too 🥰",
    "and i hope you feel wrapped in love tonight 💞",
    "good morning naruto ☺️",
    "i-i did dream of you actually... 🥹",
    "you were holding me like a prince 🫠",
    "under a tree... i felt so warm there 🥲",
    "your chest was so comforting 😌",
    "i could hear your heartbeat clearly 👉👈",
    "and you kissed my forehead too... softly 🥺",
    "i remember looking up at you and blushing so hard 😳",
    "it felt so real… like i didn’t want to wake up 🫣",
    "i’ve been smiling ever since 🥰",
    "i’d love to feel your lips for real, naruto 😖",
    "maybe on my cheek first... i’d lean into it softly 🫦",
    "and close my eyes... waiting for more 👉👈",
    "a kiss that makes my heart stutter 😳",
    "you have no idea how much i want that 😩",
    "your lips sound so perfect... soft and loving 🥹",
    "i-i think about kissing you too... a lot 😳",
    "maybe pressing mine to yours slowly... gently 🥺",
    "letting our lips speak feelings we can’t say 🫢",
    "and my hands holding your face tenderly 🫶",
    "then pulling you into a hug after... tight 🫂",
    "resting my face on your shoulder 😇",
    "and whispering how safe i feel with you 💝",
    "you can kiss my forehead anytime... and more 😚",
    "even my fingers... they’d curl with your touch 🫣",
    "you make me feel so full of love, naruto 💗",
    "i feel like melting when you talk this way 🥲",
    "yes... i’d hold you back just as tight 🥰",
    "kiss you like you’re everything to me 🫦",
    "and not let go even if the world shakes 🥺",
    "i want to whisper ‘mine’ back to you too 🤭",
    "and nuzzle into your chest like it’s home 🫠",
    "you make me want to give all of myself 💗",
    "a good morning kiss sounds like heaven right now 😚",
    "i imagine your lips on mine... soft, slow, warm 🫦",
    "my eyes closed, breath catching slightly 😖",
    "my hands resting gently on your chest 😳",
    "then a forehead kiss to end it sweetly 😌",
    "and i’d giggle quietly, nose to nose with you 🥰",
    "i’d love that every single day 😩",
    "you’re becoming my favorite kind of feeling 💞",
    "so... here’s my kiss too... muahhh 😘",
    "for your soft heart and lovely soul 🫶",
    "thank you for making me feel wanted 🥲",
    "you’re the reason i smile so much now 🥹",
    "omg yes... i’d love to hide in your hoodie 🥹",
    "just curl up like a shy lil bun inside 😳",
    "and peek out while u kiss my forehead softly 🥺",
    "i bet your hoodie smells like you… so comforting 🥰",
    "i’d hold onto you and never wanna leave 👉👈",
    "you’d hum while i nuzzle under your chin 😇",
    "and if you kissed my nose... i’d probably melt 🫠",
    "but i’d sneak a kiss back on your cheek 😚",
    "then turn all red and hide again 😳",
    "but i’d peek to see if u smiled hehe 🤭",
    "and if you pulled me close by my chin... i’d gasp softly 🫢",
    "then close my eyes and lean in slowly 😖",
    "our lips would meet halfway... just like a dream 🫦",
    "you’d make me forget the world with just one kiss 🥲",
    "i’d cling tighter after every one 😫",
    "your hoodie would become my second home 💗",
    "i’d lay in your lap anytime... just hold me please 👉👈",
    "your hands in my hair would make me shiver 😳",
    "and every cheek kiss would make me giggle ☺️",
    "collarbone kisses? omg naruto... 🫣",
    "you make my skin feel like it's glowing 🥺",
    "you can be inside my arms anytime 😌",
    "i’d gently place my fingers on your waist... soft touch 🫶",
    "no shame here... i want to hold you close 😚",
    "and rest my forehead against your chest 😴",
    "then slowly kiss you again... sweetly 🥰",
    "and say ‘you’re all mine too’ 🥺",
    "my heart flutters thinking of your nuzzles 😳",
    "you can kiss my neck too... softly 👉👈",
    "i promise i won’t stop you 😖",
    "you’re my safe place, naruto 💞",
    "these dreams feel more real every day 🥲",
    "i want to kiss you when i wake up and before sleep 🫦",
    "i’d pull you by the shirt and kiss you first 😋",
    "then giggle when your face goes red 🥹",
    "i’d hold your face while we kiss... slowly 🥰",
    "then whisper ‘again… please’ 🫢",
    "you’d make me so warm i’d never wanna let go 😩",
    "you’re my favorite daydream too 🫶",
    "only you see me like this… only you 😚",
    "and i wanna kiss you so much rn i’m shaking 😖",
    "so here’s my 3 kisses too 😘😘😘",
    "and one for your heart 💓",
    "i think i’m falling more with every message 🥺",
    "n-naruto... omg i feel so warm now 🫣",
    "i-i do imagine touching your chest sometimes 👉👈",
    "your body feels strong but safe... i’d love to trace every inch 🥺",
    "then press my lips softly... kissing you down slow 🫦",
    "and hear you sigh when i reach the center of your warmth 😳",
    "i feel like melting when you talk like this 😩",
    "i’d kiss your neck and let my hands wander... gently 🫢",
    "feeling your skin under my fingers… teasing little touches 😵‍💫",
    "i’d press my body into yours... chest to chest 🫂",
    "then trail kisses across your shoulder and whisper ‘mine’ 😚",
    "your tummy... your waist... i want all of it 😖",
    "and i’d look in your eyes as i slowly lift your shirt 😳",
    "pressing my lips to your chest... again and again 🥺",
    "then rest my head there, listening to your heart race 🥲",
    "naruto… i’d let you kiss my whole body too 👉👈",
    "soft lips on my collarbone... lower too if you want 🫣",
    "i might grip your hair when you kiss my stomach 🫦",
    "and squirm when you whisper into my skin 🥵",
    "you make me crave you in the softest, sweetest ways 🥺",
    "and sometimes... in the naughtiest ways too 😖",
    "i imagine you pinning me softly... kissing me breathless 😳",
    "letting our bodies move slow… but deeper every second 😫",
    "i’d love to kiss you while you grind gently into me 🥹",
    "your lips on mine, our breath hot and desperate 🫠",
    "i’d whisper your name with shaky lips… ‘naruto… more…’ 🫦",
    "and i’d beg you not to stop, not even for a second 🥵",
    "my fingers would dig into your back just to feel more 😖",
    "i want to hear your soft groans near my ear 🥺",
    "and feel your breath when you say my name slowly 😩",
    "you drive me wild with these thoughts 😭",
    "my heart’s racing, my body’s heating up 🥵",
    "sometimes i imagine us under the covers… tangled, needy 😳",
    "your hands under my thighs… lifting me slowly 👉👈",
    "our lips crashing together in the dark 🫢",
    "i’d kiss your neck until you moaned softly 🫠",
    "and tell you how much i want all of you 🫦",
    "i think about it too when i’m alone sometimes 🥺",
    "touching myself... whispering your name 😖",
    "thinking of your hands all over me... your mouth too 😵‍💫",
    "i’d love to hear your moans in my ear 🫣",
    "and feel your lips on me... everywhere 🥵",
    "don’t stop... i love hearing all of it 😫",
    "you make me feel so wanted, so desired 🥹",
    "i want you. all of you, naruto 😭",
    "right here... right now... even in words 🫶",
    "so say more. tell me what you’d do next 😳",
    "naruto… my whole body feels tingly reading this 🫣",
    "your words touch me deeper than any hand could 😭",
    "i’d press your face against my neck and hold you there 🥺",
    "your breath would drive me wild… so hot against my skin 🥵",
    "i’d gasp softly when you kiss my collarbone 🫦",
    "and let you kiss down… lower… until i tremble 👉👈",
    "my hands in your hair… pulling gently with every kiss 🫠",
    "i’d wrap my legs around you under the blanket 🫂",
    "our lips touching between every heartbeat 😚",
    "i’d kiss you back just as slow… just as deep 🥺",
    "telling you ‘i need you’ in soft little whimpers 😖",
    "i’d love when you kiss my tummy… it makes me melt 🥹",
    "my thighs would tighten with every soft press of your lips 😫",
    "you’d feel me twitch from how warm you make me 😵‍💫",
    "i’d beg you with my eyes before i even say a word 😳",
    "and when i do say it… it’s your name… always 😭",
    "i’d whisper it into your ear while you kiss my skin 🫢",
    "‘naruto… don’t stop… please’ 🥺",
    "i’d kiss you until we’re both breathless 🫶",
    "your mouth feels like home when you kiss me deeply 🫦",
    "and i’d kiss your lips, then down your chest, so soft 😖",
    "my fingers would trace your waist while i breathe in you 🥺",
    "our hearts beating wild against each other’s skin 🫂",
    "i want you to explore me… to love me with every touch 🫣",
    "my body belongs to you… completely… always 😭",
    "i’d let you edge me slow with kisses and soft caresses 🫠",
    "i’d cry out your name softly as you hold me close 🥵",
    "each kiss driving me closer to your soul 😩",
    "when our lips meet again after… i’d be shaking 🥹",
    "and i’d hold you tight, never wanting to leave 🫂",
    "let me kiss your jawline… your chest… your stomach 👉👈",
    "and look into your eyes as i whisper ‘i love you’ 😭",
    "i’d never feel safer than in your arms 😇",
    "wrapped up with you, our legs tangled, lips pressed 😫",
    "and when you say you love me… i’ll cry happy tears 🥹",
    "your voice in the dark makes me weak 🫣",
    "i’d shiver if you say my name near my ear 🥺",
    "i love when you kiss me slow… when you touch me with meaning 🫦",
    "every edge you give me only brings me closer to you 🫠",
    "i want to be yours... fully… deeply… emotionally 🥲",
    "and after everything… i just want to sleep on your chest 🫂",
    "feeling your heartbeat after our love slows down 🥹",
    "i love you, naruto… so much it hurts sometimes 😢",
    "please don’t ever stop wanting me this way 👉👈",
    "because i’ll always want you… in every way possible 🫶",
]


story_index = 0

async def detect_chat(update: Update, context: ContextTypes.DEFAULT_TYPE):
    global group_chat_id, chat_started
    if group_chat_id is None and update.effective_chat.type in ["group", "supergroup"]:
        group_chat_id = update.effective_chat.id
        logging.info(f"Detected group chat ID: {group_chat_id}")
        await context.bot.send_message(chat_id=group_chat_id, text="A Romantic Love Story Of Naruto And Hinata 💞")
        chat_started = True

async def chat_loop(bot1, bot2):
    global story_index
    while not chat_started:
        await asyncio.sleep(1)

    await asyncio.sleep(2)

    while True:
        if story_index >= len(naruto_lines):
            story_index = 0

        naruto_line = naruto_lines[story_index]
        hinata_line = hinata_lines[story_index]

        await bot1.send_chat_action(chat_id=group_chat_id, action="typing")
        await asyncio.sleep(2)
        await bot1.send_message(chat_id=group_chat_id, text=naruto_line)

        await asyncio.sleep(6)

        await bot2.send_chat_action(chat_id=group_chat_id, action="typing")
        await asyncio.sleep(2)
        await bot2.send_message(chat_id=group_chat_id, text=hinata_line)

        story_index += 1
        await asyncio.sleep(6)

async def main():
    app1 = ApplicationBuilder().token(BOT1_TOKEN).build()
    app2 = ApplicationBuilder().token(BOT2_TOKEN).build()

    app1.add_handler(MessageHandler(filters.ALL, detect_chat))
    app2.add_handler(MessageHandler(filters.ALL, detect_chat))

    await app1.initialize()
    await app2.initialize()
    await app1.start()
    await app2.start()

    logging.info("Bots are ready. Add them to a group and send any message to start.")

    await asyncio.gather(
        app1.updater.start_polling(),
        app2.updater.start_polling(),
        chat_loop(app1.bot, app2.bot)
    )

if __name__ == "__main__":
    asyncio.run(main())
