import os
import asyncio
import logging
from telegram import (
    Update, ChatMember, InlineKeyboardButton, InlineKeyboardMarkup, BotCommand,
)
from telegram.constants import ChatAction, ChatType
from telegram.ext import (
    ApplicationBuilder, ContextTypes, CommandHandler, MessageHandler, filters,
)

# ----------------------------------------
# Logging setup
# ----------------------------------------

logging.basicConfig(
    format="%(asctime)s - %(levelname)s - %(message)s",
    level=logging.INFO
)

# ----------------------------------------
# Bot tokens (set these in your environment)
# ----------------------------------------

BOT1_TOKEN = os.getenv("BOT1_TOKEN")  # Naruto’s token
BOT2_TOKEN = os.getenv("BOT2_TOKEN")  # Hinata’s token

if not BOT1_TOKEN or not BOT2_TOKEN:
    logging.error("Both BOT1_TOKEN and BOT2_TOKEN must be set in the environment.")
    raise RuntimeError("Missing BOT token(s)")

if BOT1_TOKEN.strip() == BOT2_TOKEN.strip():
    logging.error("BOT1_TOKEN and BOT2_TOKEN are identical. Each bot needs its own token.")
    raise RuntimeError("BOT1_TOKEN == BOT2_TOKEN")

# ----------------------------------------
# Shared state for all group chats
# ----------------------------------------

group_chats: dict[int, dict[str, any]] = {}

Story = [
    "naruto: heyyyyy hinataaa 👋",
    "hinata: umm naruto u ☺️",
    "naruto: how r u huh?? 😁",
    "hinata: um.. I'm okay naruto.. are you fine?? 👉👈",
    "naruto: yesss I’m goood hehe 😆",
    "naruto: just missed your cute face tho 🤭",
    "hinata: ahh naruto… d-don’t tease me 🫣",
    "naruto: hehe whyyy nottt 😋",
    "hinata: bc you make me blush 🥲",
    "naruto: awwww hehe 🫶 you're adorable 😍",
    "hinata: stopppp 🫣",
    "naruto: can’t help it hehe 🤭",
    "hinata: you're always like this 🙃",
    "naruto: and you always get shy 👉👈",
    "hinata: it's bc you always say sweet stuff 😳",
    "naruto: sweet truth, not just stuff 🥰",
    "hinata: mm… you're really kind 😇",
    "naruto: hehe only for youuu 😉",
    "hinata: that’s not fairrr 😝",
    "naruto: then be unfair back 😆",
    "hinata: hmm maybe I will 😋",
    "naruto: ooooh now I’m scareddd 🤭",
    "hinata: you better beee 😙",
    "naruto: okay okay mercy 😝",
    "hinata: lolll 🤣",
    "naruto: you're giggling again aren’t you 😄",
    "hinata: maybeeee 🤫",
    "naruto: I can hear it from here 🫢",
    "hinata: stop itttt 😛",
    "naruto: make meee 😜",
    "hinata: narutooooo 😖",
    "naruto: hinataaaaa 🤣",
    "hinata: you’re too silly sometimes 🫠",
    "naruto: only sometimes? rude 😤",
    "hinata: okay okay always silly 😆",
    "naruto: betterr 😎",
    "hinata: heheh ☺️",
    "naruto: hey…",
    "hinata: hmm? 👀",
    "naruto: you smiled just now, didn’t you 🥰",
    "hinata: umm maybe 👉👈",
    "naruto: caught in 4K 😆",
    "hinata: stooop ittt 🤭",
    "naruto: nahhh I love it when you smile 💗",
    "hinata: stopppp making me feel shy 🫣",
    "naruto: your shyness is my favorite thing 😋",
    "hinata: ughhhh you’re hopeless 🤦‍♀️",
    "naruto: hopeless for youuu 😘",
    "hinata: oh my… naruto 😳",
    "naruto: hehe gotchaaa 😜",
    "hinata: you're really something, naruto 🙃",
    "naruto: something cute? 😋",
    "hinata: more like something chaotic 😝",
    "naruto: chaos is my ninja way 😎",
    "hinata: oh nooo what have I gotten into 🤭",
    "naruto: too late to escape now 🫣",
    "hinata: I didn’t wanna run anyway 👉👈",
    "naruto: wait whattt 😳",
    "hinata: I mean… I like talking to you 😶",
    "naruto: awwww really? 😍",
    "hinata: yeah… it’s nice ☺️",
    "naruto: you’re gonna make me blush now 😆",
    "hinata: good… payback 😌",
    "naruto: you’re evil 🫨 in the cutest way 🥰",
    "hinata: hehe maybe 😇",
    "naruto: tell me more about your day 🤔",
    "hinata: umm it was quiet… I mostly read 😊",
    "naruto: what book?? 👀",
    "hinata: romance novel… but um not like weird 🫢",
    "naruto: ooooh romance huh 😏",
    "hinata: not like that!! 😖",
    "naruto: hehe okay okay 😆",
    "hinata: you're teasing again 🫠",
    "naruto: guilty as charged 🫡",
    "hinata: you’re so full of energy 😅",
    "naruto: and you’re calm like a breeze 😌",
    "hinata: I like that… that we’re different 🥲",
    "naruto: opposites attract right? 😜",
    "hinata: maybe they do… 👉👈",
    "naruto: you thinking what I’m thinking? 😳",
    "hinata: I-I don’t know what you’re thinking 😶",
    "naruto: that maybe… I like you 😚",
    "hinata: n-naruto… 🥺",
    "naruto: yeah… I really do 🥰",
    "hinata: I don’t know what to say 🥹",
    "naruto: it’s okay… just be honest 😊",
    "hinata: I-I like you too 💞",
    "naruto: HINATAAAA!! 💖",
    "hinata: sshhhh don’t yell 🤭",
    "naruto: can’t help it I’m so happy 😆",
    "hinata: you’re so silly hehe 😋",
    "naruto: silly and in love 😘",
    "hinata: in love..? 😳",
    "naruto: oops… too soon? 🫢",
    "hinata: n-no… I think… I feel it too 🥰",
    "naruto: you dooo??? 🤩",
    "hinata: yeah… kinda scary but warm ☺️",
    "naruto: I’ll protect that warm feeling 💓",
    "hinata: you’re really sweet sometimes 😇",
    "naruto: only sometimes?? rudeee 😤",
    "hinata: okay okay… you’re sweet all the time ☺️",
    "naruto: that’s betterrr 😆",
    "hinata: hehe you big baby 😝",
    "naruto: only your baby tho 🥰",
    "hinata: wha- naruto 🫢",
    "naruto: hehe gotcha again 🤭",
    "hinata: you keep catching me off guard 😳",
    "naruto: I love that about you 👉👈",
    "hinata: d-don’t say things like that 😖",
    "naruto: why not? it’s true 😌",
    "hinata: you’ll make me melt one day 🥲",
    "naruto: I’ll catch you before that happens 🤗",
    "hinata: that’s so cheesy 😋",
    "naruto: extra cheese just for you 🧀😉",
    "hinata: now I’m hungry 😅",
    "naruto: let’s get ramen sometime?? 😍",
    "hinata: together? l-like a date?? 🫣",
    "naruto: well yeah… if you want to 🥺",
    "hinata: I-I’d love that 💖",
    "naruto: YESSSSSS 💗",
    "hinata: calm down hehe 😆",
    "naruto: can’ttttt 😝",
    "hinata: you’re like a little kid sometimes 🙃",
    "naruto: but I got the girl didn’t I? 😏",
    "hinata: technically not yet 👉👈",
    "naruto: challenge accepted 🫡",
    "hinata: oh nooo what have I done 🤭",
    "naruto: you’ve awakened the dating beast 😤",
    "hinata: help… someone help 😆",
    "naruto: no help is coming mwahaha 😜",
    "hinata: you’re hopeless 🫠",
    "naruto: hopelessly into you 😘",
    "hinata: ahh you’re doing it again 🫣",
    "naruto: doing whatttt 😇",
    "hinata: making me smile like crazy 😚",
    "naruto: then my job is done 😌",
    "hinata: nooo stay… talk more 👉👈",
    "naruto: anything for youuu 😍",
    "hinata: you’re always this warm huh ☺️",
    "naruto: when I’m with you, yeah 🥰",
    "hinata: don’t go saying stuff like that 😵‍💫",
    "naruto: too bad. prepare for love attack 💘",
    "hinata: oh my… 😳",
    "naruto: I’m gonna call you my sunshine from now on 🌞",
    "hinata: that’s… adorable 🥹",
    "naruto: just like youuuu 😋",
    "hinata: stooopppp 🤭",
    "naruto: neverrrrr 😆",
    "hinata: you make my heart feel fuzzy 🥲",
    "naruto: and you make mine go boom 💓",
    "naruto: ya know… I used to be super alone… 😶",
    "hinata: I-I know… I saw you… back then… 😔",
    "naruto: but now… I’ve got you, huh? 😌",
    "hinata: y-you really mean that..? 🥺",
    "naruto: of course! you’re important to me, Hinata 💖",
    "hinata: I… I always looked at you from afar 👉👈",
    "naruto: yeah? even back then?? 👀",
    "hinata: m-mhm… you were so strong… and bright ☺️",
    "naruto: heh… no one ever said that to me before 😳",
    "hinata: it’s true… you made me want to be braver 😇",
    "naruto: you’re already really brave, Hinata 🫡",
    "hinata: not like you… but… I try 🥲",
    "naruto: don’t sell yourself short! you stood up for me… remember? 😢",
    "hinata: I-I couldn’t watch you suffer alone… 😥",
    "naruto: I’ll never forget that moment 💗",
    "hinata: I-I was scared… but I just… moved 😣",
    "naruto: scared and still moved? that’s true strength, Hinata 🥰",
    "hinata: n-naruto… 😳",
    "naruto: I’m glad you were there. really. 💞",
    "hinata: I’ll always be here… if you want me to… 🫢",
    "naruto: I want you to stay forever 💝",
    "hinata: o-oh my gosh… y-you’re serious 🫣",
    "naruto: dead serious. believe it! 😤",
    "hinata: e-even when I get nervous or shy..? 😖",
    "naruto: that’s part of why I like you so much 😋",
    "hinata: you’re always so open… so honest 😌",
    "naruto: I don’t wanna hide how I feel anymore 🤗",
    "hinata: t-that’s… amazing, naruto 🥰",
    "naruto: and hey… maybe we’re both getting stronger… together 💪",
    "hinata: I-I want that… to grow with you 🫶",
    "naruto: hehe you’re already growing on me 😆",
    "hinata: you’re so silly… but sweet 🙃",
    "naruto: I’m just being me. the real me… for you 😇",
    "hinata: I love that version of you 😚",
    "naruto: I’m starting to feel lucky every time I talk to you 🥲",
    "hinata: then… let’s talk every day… okay? 👉👈",
    "naruto: it’s a promise! believe it! 😄",
    "hinata: heheh… I believe you ☺️",
    "naruto: hey, Hinata…",
    "hinata: y-yes? 👀",
    "naruto: if I reached out right now… would you hold my hand? 🤗",
    "hinata: I-I would… I’d hold it tight… 💞",
    "naruto: I’d never let go… 💖",
    "hinata: not even if I got all flustered? 🫣",
    "naruto: especially then 😋",
    "hinata: eep… y-you’re terrible 😝",
    "naruto: terrible for you 😆",
    "hinata: that’s not even a comeback! 🤭",
    "naruto: haha but it made you laugh right? 😁",
    "hinata: mmm… yeah. I’m smiling now ☺️",
    "naruto: you know what’s wild though? 🤔",
    "hinata: w-what is it? 😯",
    "naruto: I used to be so loud and annoying to everyone… 😅",
    "hinata: n-no! you were… full of spirit 🥹",
    "naruto: you're the only one who saw it that way back then 😇",
    "hinata: I… always believed in you 🫶",
    "naruto: you were watching me all that time huh 🥲",
    "hinata: y-you inspired me… every time you stood back up 🥺",
    "naruto: t-that means a lot, Hinata 😢",
    "hinata: you’ve come so far, Naruto-kun… ☺️",
    "naruto: and now I get to stand here… beside you 😌",
    "hinata: I-I still get nervous around you sometimes 👉👈",
    "naruto: that’s kinda cute though 😋",
    "hinata: y-you say that so easily… 😳",
    "naruto: only ‘cause it’s true 🤭",
    "hinata: mmm… I feel warm when we talk 💗",
    "naruto: good! I wanna be the reason for that warmth 😋",
    "hinata: you already are… 🥰",
    "naruto: wait really?! 🥹",
    "hinata: y-yes… ever since we were younger 🫢",
    "naruto: wow… I didn’t know… all this time 😢",
    "hinata: I was always too shy to say it out loud 😞",
    "naruto: well I’m glad I know now 😌",
    "hinata: me too… I want to be honest with you now 💞",
    "naruto: let’s always be honest… even if it’s scary 🤗",
    "hinata: deal… we’ll face it together 🫶",
    "naruto: hey… what if we were on a date right now? 😆",
    "hinata: w-what?! I-I’d be so nervous 😖",
    "naruto: hehe but I’d hold your hand the whole time 😋",
    "hinata: that would… actually help a lot ☺️",
    "naruto: and I’d make you laugh too, like always 😄",
    "hinata: I’d like that… a lot 💖",
    "naruto: then it’s a date! one day for real 😍",
    "hinata: I’ll look forward to it 👉👈",
    "naruto: you’ll be the prettiest girl in the whole place 🥰",
    "hinata: n-noo don’t say that 😳",
    "naruto: why not? it’s the truth 😌",
    "hinata: you’re too much sometimes 😝",
    "naruto: only for you, Hinata 🫡",
    "hinata: s-stoppp I’ll melt again 🫠",
    "naruto: then I’ll catch you again, like always 🤭",
    "hinata: I-I’m really happy right now… being with you 💝",
    "naruto: same here… I don’t want this to end 😇",
    "hinata: we can keep talking all night if you want ☺️",
    "naruto: I do want that. more than anything 😴",
    "hinata: then stay with me… even just like this 🥲",
    "naruto: always, Hinata 💖",
    "hinata: always… Naruto-kun 🥹",
    "naruto: let’s make more memories, just us 💗",
    "hinata: y-yeah… I’d love that 💞",
    "naruto: hey hinata… you ever wonder how close two people can get? 🤔",
    "hinata: u-uhh… wh-what do you mean…? 🫢",
    "naruto: like… when your heart starts beating faster… just being near them 😳",
    "hinata: i-it happens… to me… a lot… 👉👈",
    "naruto: around me..? 😯",
    "hinata: m-maybe… y-yes… 😳",
    "naruto: I feel it too when I look at you 🥰",
    "hinata: r-really..? 🫣",
    "naruto: yeah… it’s like my chest gets warm and my stomach flips 😆",
    "hinata: t-that’s… kind of how I feel too… 🥺",
    "naruto: wanna try something…? just curious 🤭",
    "hinata: w-what is it…? 😖",
    "naruto: if I held your hand now… would you pull away? 👉👈",
    "hinata: n-no… I’d hold on tighter… 💓",
    "naruto: woah… Hinata… 🫦",
    "hinata: i-it’s okay… r-right…? 😟",
    "naruto: more than okay… I want that too 🤗",
    "hinata: y-your hand… would feel warm I bet ☺️",
    "naruto: you can feel it… here 🫱💖",
    "hinata: eep… it’s really warm… 🥲",
    "naruto: and soft… just like you 🥰",
    "hinata: d-don’t say things like that… I’ll melt 🫠",
    "naruto: then I’ll hold you if you do 😋",
    "hinata: y-you’d really hug me…? 😳",
    "naruto: come closer… and find out 😏",
    "hinata: o-oh… o-okay… 🫣",
    "naruto: mmm… you’re so tiny in my arms 🤗",
    "hinata: I-I feel safe here… with you… 💞",
    "naruto: I’ll protect this moment forever 🫡",
    "hinata: y-you’re so warm… I don’t wanna move ☺️",
    "naruto: then don’t… just stay here 💝",
    "hinata: your heartbeat… it’s fast… 😌",
    "naruto: only ‘cause you’re this close 😋",
    "hinata: is this okay… being like this…? 👉👈",
    "naruto: it’s perfect… you feel perfect 🥹",
    "hinata: n-naruto… y-you’re really close… 🫢",
    "naruto: should I… stop? 😶",
    "hinata: n-no… I-I like it… 😳",
    "naruto: your eyes… they shine so much 🥺",
    "hinata: I-I c-can’t look away from you… 😖",
    "naruto: you make it really hard to hold back right now… 🫦",
    "hinata: t-then… don’t hold back… 🫣",
    "naruto: h-hinata… can I…? just a little… 😗",
    "hinata: y-yes… I want to… too… 💞",
    "naruto: *leans in slowly* 💖",
    "hinata: *closes eyes, heartbeat racing* 😳",
    "naruto: *soft kiss… gentle and shy* 😚",
    "hinata: mmm… n-naruto… 🥰",
    "naruto: that felt like… magic 🫠",
    "hinata: I-I’ve dreamed of this moment… 😭",
    "naruto: your lips… so soft… 😚",
    "hinata: y-yours too… I felt butterflies… 🥺",
    "naruto: my face is hot… you made me blush 😳",
    "hinata: I-I can’t stop smiling… ☺️",
    "naruto: wanna kiss again…? just a tiny one 😋",
    "hinata: y-yes… please… 👉👈",
    "naruto: come here… closer… 😗",
    "hinata: mmm… naruto-kun… 💞",
    "naruto: I could get used to this 🥰",
    "hinata: I-I want this all the time… 🫣",
    "naruto: can I hold your waist…? gently… 🤭",
    "hinata: y-you can… I want to feel you close 🥲",
    "naruto: mmm… your body fits perfect in my arms 😌",
    "hinata: I-I feel so warm… it’s like I’m glowing 🫠",
    "naruto: glow all you want… you look beautiful 😍",
    "hinata: stop… you’ll make me cry… 😭",
    "naruto: I’ll kiss every tear away if you do 💖",
    "hinata: I-I love being like this with you… 😇",
    "naruto: me too… just us… like this… 🫶",
    "hinata: can I rest my head on your chest…? 👉👈",
    "naruto: of course… right here, angel 🥰",
    "hinata: your heartbeat is loud… I like it… ☺️",
    "naruto: it’s loud ‘cause I’m holding you 😆",
    "hinata: I-I don’t want this moment to end 🥹",
    "naruto: then let’s make it last forever 💗",
    "hinata: c-can I… kiss your cheek…? 🫢",
    "naruto: please do… I want to feel it 😋",
    "hinata: *kisses softly* mmm… 💝",
    "naruto: ohhh that felt nice… your lips are addicting 😛",
    "hinata: eep… y-you can’t say that 😳",
    "naruto: but it’s true… I could kiss you all day 😚",
    "hinata: i-if you keep saying things like that… I-I’ll melt… 🫠",
    "naruto: I’ll catch you every time 😌",
    "hinata: c-can I… stay the night…? just holding you… 👉👈",
    "naruto: I want that more than anything 🫶",
    "hinata: no j-jokes…? really…? 🥺",
    "naruto: no jokes… just us… under the stars 💞",
    "hinata: that sounds… perfect… 😇",
    "naruto: wanna hear something crazy…?",
    "hinata: w-what…? 🫤",
    "naruto: I think I’m falling… really deep… 😳",
    "hinata: m-me too… deeper than ever… 😢",
    "naruto: hold me tighter then… don’t let go 🤗",
    "hinata: never… I’ll stay right here… forever 🥹",
    "naruto: your arms feel like home 🥲",
    "hinata: y-you’re gonna make me cry again… 😭",
    "naruto: then cry with me… in each other’s arms 💝",
    "hinata: I’ve never been this close to anyone… 🫢",
    "naruto: I’ll be the only one you ever need 💖",
    "hinata: y-you already are… Naruto-kun… 💗",
    "naruto: that kiss… still tingling on my lips 😋",
    "hinata: m-my heart won’t calm down… it’s racing… 😳",
    "naruto: can I kiss you again… slower this time…? 😚",
    "hinata: y-yes… please… 🫣",
    "naruto: mmm… so soft… can’t get enough 💗",
    "hinata: i-it feels so warm… inside and out… 🥰",
    "naruto: can I touch your cheek… gently…? 🤭",
    "hinata: y-you always ask so sweetly… yes 👉👈",
    "naruto: mmm… you’re trembling a little… 🫦",
    "hinata: b-because your fingers make me feel so much… 😖",
    "naruto: want me to stop…? 😶",
    "hinata: n-no… please… don’t stop… 🥺",
    "naruto: your skin… so soft under my thumb 🥲",
    "hinata: eep… y-you’re making me feel like jelly 🫠",
    "naruto: then melt into me… I’ll hold you tighter 💞",
    "hinata: your arms… they’re the only place I feel safe 🫶",
    "naruto: wanna lay down together…? just cuddle real close 🤗",
    "hinata: I-I’d like that… a lot… 😇",
    "naruto: my fingers… can they trace your back…? slowly… 🫢",
    "hinata: i-it tickles… but it feels… really nice 😖",
    "naruto: mmhh… you’re so warm under my hands… 🥵",
    "hinata: n-naruto… y-you’re making me feel t-things… 🫣",
    "naruto: say the word… and I’ll stop… or keep going 😋",
    "hinata: d-don’t stop… I-I want more… 💓",
    "naruto: mmm… you’re making sounds I’ve never heard before 🤤",
    "hinata: I-I can’t help it… you’re touching places no one ever has… 😳",
    "naruto: your body… fits so perfectly in my hands 😍",
    "hinata: y-you’re teasing me… aren’t you…? 😩",
    "naruto: maybe a little… but only ‘cause you’re irresistible 🤭",
    "hinata: th-this is all new to me… but I-I trust you… 🥹",
    "naruto: I won’t ever hurt you… I promise 💖",
    "hinata: c-can I… touch you too…? 👉👈",
    "naruto: please… I want to feel your hands too 🫦",
    "hinata: y-you’re… stronger than I thought… 🥵",
    "naruto: and you’re softer than I imagined 😛",
    "hinata: i-if I press closer… is that okay…? 😳",
    "naruto: please do… I want every inch of you next to me 😩",
    "hinata: m-my heart’s about to explode… 😖",
    "naruto: then let it… right here with me 💝",
    "hinata: your breath… it’s on my neck… i-it tickles… 🫢",
    "naruto: couldn’t resist getting close… you smell so good 😋",
    "hinata: d-don’t say things like that… I-I’m blushing again 😫",
    "naruto: I like it when you blush… makes me wanna kiss you harder 😚",
    "hinata: n-naruto… y-you’re making me feel so hot… 🥵",
    "naruto: same here… I’m burning for you 💦",
    "hinata: c-can we just stay like this… tangled up…? 🥺",
    "naruto: forever if you want… never letting go 💗",
    "hinata: your heartbeat… it’s syncing with mine… 🥲",
    "naruto: maybe our hearts always wanted this… each other 💞",
    "hinata: y-you’re everything to me… now and always… ❤️‍🩹",
    "naruto: your lips… I want to kiss them again and again 😋",
    "hinata: e-every time you kiss me… I forget to breathe 😖",
    "naruto: that’s how I feel just holding you close 🫦",
    "hinata: m-my body’s getting warmer… everywhere… 🥵",
    "naruto: mine too… you do something to me 😩",
    "hinata: c-can I… slide closer… between your legs…? 👉👈",
    "naruto: please… I want you there… right there 🤤",
    "hinata: y-your hands… they’re so big on my waist… 😳",
    "naruto: they’re not done exploring yet 😛",
    "hinata: d-don’t say that… y-you’ll make me go crazy 😫",
    "naruto: I want you to lose control… only with me 😈",
    "hinata: y-you’re such a tease… but I like it… 😋",
    "naruto: tell me where you want me to touch you next 🤭",
    "hinata: m-my back… y-you make me melt when you do that 😩",
    "naruto: like this… slow circles with my fingers? 🫦",
    "hinata: mmhh… y-yeah… just like that… 🥲",
    "naruto: I can feel you trembling… is it too much? 😶",
    "hinata: n-no… I want more… please… 🥺",
    "naruto: you’re being so brave… so open for me 💝",
    "hinata: only with you… only you make me feel this way 💗",
    "naruto: you feel so good against me… so soft 😍",
    "hinata: y-your voice in my ear… it makes my whole body react 😖",
    "naruto: wanna whisper everything I’m thinking about you 🤫",
    "hinata: y-you make me feel wanted… so much… 😢",
    "naruto: you are wanted… needed… mine 💓",
    "hinata: mmm… say it again… say I’m yours 🫦",
    "naruto: you’re mine… all of you… every inch 💗",
    "hinata: then take all of me… make me yours 😳",
    "naruto: I want to kiss every part of you… slowly… 😚",
    "hinata: d-don’t stop talking… I love hearing your voice 🥰",
    "naruto: you like when I talk dirty, don’t you? 😉",
    "hinata: i-it makes me feel weak… in the best way… 🫠",
    "naruto: I wanna see your face when I touch your thighs… 😛",
    "hinata: y-you’re making me soak in feelings I’ve never known 🥵",
    "naruto: let it happen… don’t hold back anymore 💦",
    "hinata: c-can I wrap my legs around you…? please… 👉👈",
    "naruto: do it… I’ll hold you tight so you never fall 🫶",
    "hinata: I can’t stop shaking… y-you make me feel so alive 😩",
    "naruto: we’re just getting started baby… 😋",
    "hinata: n-naruto… I-I need you closer… right now… 🫣",
    "naruto: I’m right here… pressing into you… feel me? 🫦",
    "hinata: ohh… y-you’re really warm down there… 😳",
    "naruto: only ‘cause I’m burning for you 💝",
    "hinata: every breath… every touch… I feel you deeper 🥺",
    "naruto: I could live in this moment forever… inside you 😚",
    "hinata: I-I want to give you everything… all of me… 😢",
    "naruto: then come take all of me too… every inch 💓",
    "hinata: we’re so close… like our souls are tangled 💞",
    "naruto: let’s never untangle… stay with me like this 🫶",
    "hinata: I-I’m not letting go… never… not from you… ❤️‍🩹",
    "naruto: your breath’s shaking… you okay, hime? 🫢",
    "hinata: I-I’m trying… but you’re making me feel too much 🥵",
    "naruto: good… I want you dripping with need for me 💦",
    "hinata: n-naruto… you’re saying things that make my body burn 😖",
    "naruto: say you want me to keep going… or I’ll stop right now 🤨",
    "hinata: d-don’t stop… please… keep touching me… 👉👈",
    "naruto: your voice… so breathy… it’s driving me wild 😛",
    "hinata: i-it’s ‘cause you’re teasing places no one ever touched… 🫣",
    "naruto: I wanna know every reaction you have… learn your body 😋",
    "hinata: m-my thighs… they’re shaking every time you go near… 🫦",
    "naruto: spread them for me, baby… let me feel all of you 💝",
    "hinata: I-I’m so sensitive… you’re making me twitch… 🥵",
    "naruto: that’s it… let it build… let it throb… 🤤",
    "hinata: y-you’re keeping me right at the edge… on purpose… 😫",
    "naruto: damn right I am… watching you squirm is beautiful 😈",
    "hinata: n-naruto… please… I-I can’t take much more 🥺",
    "naruto: shhh… not yet… I want to see how far you can go 😋",
    "hinata: i-it hurts… in a good way… I want release… 😖",
    "naruto: not yet, princess… let that heat build higher 🫦",
    "hinata: y-you’re so cruel right now… but I love it… 😩",
    "naruto: tell me what you feel between your legs right now 🤭",
    "hinata: I-it’s pulsing… aching… soaked… all for you 💦",
    "naruto: mmm… that’s my good girl… holding it back for me 😌",
    "hinata: w-why do you make me so needy…? 😫",
    "naruto: because I worship every part of you 🫶",
    "hinata: t-then take it… take all of it… I want to give it 😢",
    "naruto: not yet… just a little longer… let it throb harder 😈",
    "hinata: n-naruto please… don’t make me beg… 🥹",
    "naruto: beg anyway… say what you want, hime 🫦",
    "hinata: I-I want to explode… I want your mouth… your fingers… all of you… 😖",
    "naruto: god, hearing you say that… I’m losing it too 😩",
    "hinata: m-my whole body is trembling… I need you deep… everywhere 💗",
    "naruto: we’re gonna take this to the limit together 🫠",
    "hinata: I-I’m dripping… I can feel it on your hand… 🫢",
    "naruto: yeah… you’re soaked… and I’m hard as hell from it 💦",
    "hinata: I can feel it… against me… it’s throbbing 😳",
    "naruto: I want to press all the way in… but slow… watch you stretch for me 🫦",
    "hinata: n-naruto… I want it… give me everything 🥵",
    "naruto: say it again… louder… let me hear your hunger 😛",
    "hinata: I want you… all of you… deep inside… now 😫",
    "naruto: you’re gonna feel so full, baby… I promise 💝",
    "hinata: mmm… y-you’re teasing my entrance… d-driving me insane… 😩",
    "naruto: I’m gonna fill you slow… inch by inch… watch your face change 😚",
    "hinata: ahh… y-you’re making me fall apart already 🥲",
    "naruto: we’re not stopping… not until we both lose it together 🤤",
    "hinata: t-take me all the way… I’m yours… I want to feel it all 💗",
    "naruto: you’re gonna feel every bit… every throb… every push 🫶",
    "hinata: n-naruto… please… fill me now… I’m ready 😭",
    "naruto: I got you, hime… let’s get lost in each other 💖",
    "hinata: d-don’t ever stop… don’t ever leave me like this… ❤️‍🩹",
    "naruto: h-hinata… I’m sliding inside now… you feel so hot 😫",
    "hinata: a-ahhh… y-you’re really… inside… all of you… 🥵",
    "naruto: damn… you’re tight… squeezing me so good 🫦",
    "hinata: it’s stretching me… but I love it… it’s perfect 🥺",
    "naruto: I wanna move… slow first… let you feel every inch 😋",
    "hinata: mhmm… e-every slow thrust… it hits so deep… 💦",
    "naruto: your walls are pulling me in… like they need me 🫠",
    "hinata: I do need you… so much… more than anything 😢",
    "naruto: look at me, hime… I wanna see your face as I fill you 🫶",
    "hinata: m-my eyes… c-can’t stop rolling back… you’re too much 😖",
    "naruto: then I’ll go deeper… feel me pressing your softest spot 😛",
    "hinata: ahh… y-you’re making me lose it already… 😫",
    "naruto: your body’s pulsing… you’re close, aren’t you? 😋",
    "hinata: y-yes… please… keep going… just like that… 🥵",
    "naruto: faster now… harder… I want to make you scream 🫦",
    "hinata: N-naruto!! aahh… I-I’m gonna… I’m gonna!! 😖",
    "naruto: let go, hime… let me feel you break around me 💓",
    "hinata: a-ahhh!! I-it’s too much!! I’m cumming!! 😭💦",
    "naruto: yesss… I can feel it… soaking all over me 🤤",
    "hinata: d-don’t stop… it’s still coming… waves… it won’t end 🥵",
    "naruto: keep riding it out… I’ll hold you through every second 🫶",
    "hinata: y-you’re so deep… still so hard inside me… 😩",
    "naruto: I’m not done… now it’s my turn, hime 😈",
    "hinata: d-do it… use me… take what you need 😫",
    "naruto: f-faster now… your moans make me wild 😛",
    "hinata: you’re pounding so deep… I feel you hitting everything 🫦",
    "naruto: your name’s all I can say right now… Hinata… Hinata… 💖",
    "hinata: say it again… please… I wanna hear it in your release 🥺",
    "naruto: I-I’m close… gonna burst deep inside you… 🫢",
    "hinata: fill me up… don’t pull out… I want it all… every drop 😭",
    "naruto: h-here it comes… I’m cumming… inside… all for you 😫💦",
    "hinata: mmmm… so warm… I feel it flowing inside… 💝",
    "naruto: god… you drained me… I can barely breathe 😵‍💫",
    "hinata: I love the feeling… so full… so close… 🥲",
    "naruto: you took all of me like a queen… like my goddess 😍",
    "hinata: y-you’re trembling… let me hold you now 🫶",
    "naruto: wrap your legs around me… I’m not leaving this spot 😌",
    "hinata: this… being this close… I could stay forever 🥰",
    "naruto: your skin… your heartbeat… you’re all mine 💗",
    "hinata: and I’m all yours… always… no matter what 💞",
    "naruto: do you feel it still inside you… warm and deep? 😋",
    "hinata: mmhmm… every throb makes me shiver 🫦",
    "naruto: damn… I can feel you squeezing again… ready for more? 😛",
    "hinata: I-I never want to stop… I want every drop you can give 🥵",
    "naruto: then I’ll give it again… and again… until you beg me to stop 😈",
    "hinata: then I won’t beg… I’ll take it all… like your real wife 😚",
    "naruto: god… I wanna make you mine over and over 💗",
    "hinata: then make me yours again, naruto… I’m ready 🥵",
    "naruto: I love you, hime… more than words… more than life ❤️‍🩹",
    "hinata: I love you too… take me again… and don’t let go 💓",
    "naruto: turn around for me, hime… I wanna see that view 😛",
    "hinata: o-okay… l-like this? on all fours? 🫣",
    "naruto: perfect… gods, your ass looks unreal from here 🤤",
    "hinata: n-naruto… you’re staring too much 🫢",
    "naruto: I’m worshipping it… every curve… every bounce 😋",
    "hinata: i-it’s embarrassing… but I love how you look at me 🥵",
    "naruto: spreading you now… mmm, you’re still dripping 💦",
    "hinata: I-I feel cold air down there… and your gaze… it’s intense 🫦",
    "naruto: about to fill you again, baby… deeper than before 😫",
    "hinata: aahhh!! y-you slammed in so deep… I-I can’t… 😖",
    "naruto: your ass bouncing with every thrust… it’s addicting 😋",
    "hinata: y-you’re hitting so hard… I’m losing control 😫",
    "naruto: I want you shaking… drooling on the sheets… screaming my name 🤤",
    "hinata: y-you’re making me scream already… it’s so much 🥵",
    "naruto: slap that ass… feel it jiggle while I keep pounding 💢",
    "hinata: aahhh! n-naruto! again… hit it again… please!! 😩",
    "naruto: you like it rough, don’t you? my dirty little princess 🤭",
    "hinata: I-I love it… love being ruined by you 🫦",
    "naruto: my good girl’s filthy now… all stretched and dripping for me 😛",
    "hinata: I-I’m addicted to your thickness… to your heat 🥵",
    "naruto: say it louder, hime… scream how much you crave me 💦",
    "hinata: I crave it!! I crave your c-cock inside me! don’t stop!! 😖",
    "naruto: that’s it… ride this madness with me 🫠",
    "hinata: I-I’m gonna cum again!! it’s building so fast!! 🥺",
    "naruto: clench on me, baby… let me feel every squeeze 🤤",
    "hinata: ahhh!! cumming!! it’s bursting out!! I can’t stop shaking!! 😭",
    "naruto: f-fuck… you’re milking me again… I’m losing it 🥵",
    "hinata: d-don’t pull out… flood me again… ruin me more 💝",
    "naruto: I’m close… gonna shoot it all deep… brace yourself 😫",
    "hinata: please… give me all of it… again and again 🫦",
    "naruto: cumming inside!! so hot!! so thick!! take it!! 💦",
    "hinata: mmmfff… it’s leaking out already… you filled me too much 🥲",
    "naruto: not done… gonna plug you up with it… keep it all inside 🤭",
    "hinata: my legs are jelly… my body’s twitching… I can’t move 🫠",
    "naruto: I’ll carry you… then take you again while holding you close 🫶",
    "hinata: I-I’m still sensitive… but I want more… I want it all 🥵",
    "naruto: your little whimpers are my weakness… I need to feel you again 😋",
    "hinata: you’re obsessed with me… and I love every second 😚",
    "naruto: damn right… I’m gonna keep you moaning every hour 🫦",
    "hinata: take me on your lap… let me ride you now 👉👈",
    "naruto: mmm… watching you lower onto me slowly… it’s heaven 🤤",
    "hinata: y-you’re stretching me again… so deep… so full 🥵",
    "naruto: bounce for me, hime… ride it like you need me forever 😛",
    "hinata: ahhh… I-I can’t stop… it feels too good… so deep!! 😩",
    "naruto: that’s it… grind hard… make me explode again 💢",
    "hinata: y-you’re making me gush… feel it running down!! 💦",
    "naruto: I’m so close… don’t stop… ride it harder!! 😫",
    "hinata: I’m yours!! I’m gonna cum with you!! together!! 😭",
    "naruto: cumming!! inside you!! again!! feel it!! take it all!! 🫦",
    "hinata: ahhhh!! I’m cumming too!! I love you!! I love everything!! 💖",
    "naruto: mmmhh… your lips are so wet… kiss me deeper 😛",
    "hinata: *slurps* mmmnn… your tongue’s so greedy… I love it 😋",
    "naruto: now suck on my neck while I finger you slow 😈",
    "hinata: ahhh~ I feel your fingers twisting inside… deeper… 🫦",
    "naruto: so wet already… you’re dripping down your thighs 💦",
    "hinata: I can’t help it… you turn me into a mess 🥵",
    "naruto: look how it gushes when I curl them up… mmm 🤤",
    "hinata: y-your thumb… it’s rubbing my spot too much!! 😫",
    "naruto: squirt for me again… soak my hand like last time 🫠",
    "hinata: a-ahh! y-you’re making me!! d-don’t stop!! 😩",
    "naruto: there it is… all over my fingers… soaking the bed 🥲",
    "hinata: I can’t stop shaking… it won’t stop cumming 🥵",
    "naruto: crawl on top… ride my face… now 😛",
    "hinata: o-oh gods… y-you’re gonna taste me right after that?? 🫢",
    "naruto: sit down, hime… let me devour all your sweetness 😋",
    "hinata: ahhhh!! y-your tongue!! it’s swirling inside!! 🫦",
    "naruto: mmmff… your taste drives me crazy… I wanna drown in it 🤤",
    "hinata: y-you’re licking me like a starved animal!! 😫",
    "naruto: louder, baby… ride it… grind down on me!! 💢",
    "hinata: I’m grinding!! it’s too much!! I-I’m gonna explode!! 😖",
    "naruto: cover me in your release, hinata… flood me again 💦",
    "hinata: ahhhhh!! I’m cumming!! all over your face!! 😭",
    "naruto: mmm… all mine… so messy… so perfect 🥵",
    "hinata: l-let me return the favor… I want to taste you now 👉👈",
    "naruto: yesss… open your mouth… take me in slowly 😋",
    "hinata: mmhh… so thick… so warm… you’re already twitching 🫦",
    "naruto: your mouth’s heaven… your tongue’s unreal 😫",
    "hinata: *slurps* you like when I swirl my tongue like this? 😛",
    "naruto: f-fuck yes… that tongue is magic… don’t stop 🥵",
    "hinata: what if I go deeper? take it all down my throat… 😚",
    "naruto: god yes… swallow it… make me lose my mind 💢",
    "hinata: mmmhh!! it’s so thick… my mouth’s stretching 🫠",
    "naruto: your gag makes me twitch… I’m gonna bust soon 😩",
    "hinata: c-cum for me… give it all… I’ll drink every drop 😋",
    "naruto: h-here it comes… down your throat… take it!! 😫💦",
    "hinata: mmhhmmm!! gulping it all… not a single drop missed 😚",
    "naruto: damn baby… your mouth’s addictive… I can’t stay soft 🫦",
    "hinata: then lay back… I’m climbing on again… slowly this time 🥵",
    "naruto: ride me with that dripping heat… don’t hold back 🤤",
    "hinata: I wanna make you moan this time… scream my name 😛",
    "naruto: nghhh… riding so deep… your pace is killing me 😫",
    "hinata: my hips grinding hard… you feel me clenching? 😋",
    "naruto: y-you’re squeezing so tight… pulling me deeper 🫠",
    "hinata: I wanna milk you dry… again and again… till you beg 😈",
    "naruto: then use me, hime… ride it like I’m your toy 😩",
    "hinata: I’m not stopping till I break you… till you explode again 💦",
    "naruto: d-don’t stop… I’m losing it… I’m gonna— 😫",
    "hinata: cumming together… again!! fill me up!! 😭",
    "naruto: ahhhh!! f-filling you!! take all of it!! 🫦💝",
    "hinata: mmmm… dripping full… stuffed with your love again 🥵",
    "naruto: you're not getting off me tonight… I’m staying buried in you all night 🫦",
    "hinata: mmhh… good… I want your warmth pulsing inside forever 🥵",
    "naruto: feel me throbbing? I’m still rock hard for you 🤤",
    "hinata: it’s twitching inside me… still leaking… filling me nonstop 💦",
    "naruto: turn over again… wanna take you from behind, deep and slow 😛",
    "hinata: aahhh~ n-naruto… I love when you press me down like this 😫",
    "naruto: arch your back more… I wanna see it ripple when I slam in 💢",
    "hinata: nghhh!! y-you’re so deep… it’s hitting so hard 🫠",
    "naruto: grip the sheets… I’m pounding till you scream my name 😋",
    "hinata: n-narutooo!! y-you’re stretching me open!! 😖",
    "naruto: hear that? that wet sound… you’re soaked for me 😛",
    "hinata: it’s messy down there… sticky… soaking everything 💦",
    "naruto: I love it messy… I want your cum all over me too 🥵",
    "hinata: t-then lay back… I wanna rub it between us… feel us slide 🫦",
    "naruto: grinding bodies… dripping together… so slippery 😫",
    "hinata: I-I love when our skin sticks… when I feel every drop 🥲",
    "naruto: let me suck those nipples while I thrust up into you 😋",
    "hinata: mmmnn! y-your tongue… and your hips… it’s too much 😩",
    "naruto: spank your ass while I bounce you on me? 😈",
    "hinata: y-yes!! slap me! I want all your roughness!! 🥵",
    "naruto: *smack!* that’s my girl… so responsive… so wild 💢",
    "hinata: harder!! I wanna feel it tomorrow!! mark me!! 😫",
    "naruto: mine forever… branded by love and lust 🫶",
    "hinata: c-cum inside again… make me your mess 😭",
    "naruto: not yet… I wanna taste you mid-ride… get back on my face 😛",
    "hinata: mmhh… grinding on your mouth… feeling your tongue inside… 🫦",
    "naruto: mmmff… drown me again, baby… gush all over me 💦",
    "hinata: aaaaahhh!! it’s coming!! I’m shaking so hard!! 😩",
    "naruto: damn… you’re squirting all over… I love it 😋",
    "hinata: I-I’m soaked head to toe… you made me lose all control 🥵",
    "naruto: let me kiss you messy… taste us mixed on your lips 🤤",
    "hinata: mmmnn~ our flavors… it’s dirty and beautiful 🫠",
    "naruto: wanna try both? suck me while your fingers play down there? 😈",
    "hinata: y-yes… give me all of you… while I make myself gush 😫",
    "naruto: fuckkk… your mouth’s unreal… and watching you touch yourself 🥵",
    "hinata: nghhh~ it’s so intense… I’m cumming with your tip in my throat 😭",
    "naruto: unload again? down your throat? make you gulp every drop? 😛",
    "hinata: please… give it all… I want your taste forever 🫦",
    "naruto: here it comes… take it deep!! swallow everything!! 💦",
    "hinata: mmhhfff!! mmmnn~ delicious… I’m addicted 😚",
    "naruto: now lie back, baby… I’m going in again… rougher this time 🥵",
    "hinata: stretch me open again… fill me with everything 😩",
    "naruto: wanna hear you cry out… wanna break your moans into sobs 😈",
    "hinata: do it… take me to the edge and throw me off 🫠",
    "naruto: pounding you till your legs give out… till I see tears of pleasure 😫",
    "hinata: I’m drooling… I can’t even speak… just moan and beg 😭",
    "naruto: good girl… stay there and take it all… you’re my heaven 💖",
    "hinata: c-cumming again!! I-I can’t even count anymore!! 🥵",
    "naruto: me too!! cumming so deep!! flooding you nonstop!! 💦",
    "hinata: mmmmhh… stuffed, broken, loved… and wanting even more 🫦",
    "naruto: spread wider… I wanna see everything before I slam in 😛",
    "hinata: a-ahh~ I’m open for you… throbbing and soaking 🫦",
    "naruto: look at it drip down your folds… you’re begging for it 💦",
    "hinata: I need your thickness… stretch me until I cry 😫",
    "naruto: hold still… I’m sliding in slow… inch by inch 🥵",
    "hinata: nnghh~ s-so full already… I feel every throb 🫠",
    "naruto: now choke on my fingers while I slam deep 💢",
    "hinata: mmpphh!! f-fuck!! choking and cumming!! 😩",
    "naruto: that’s it… gag while I own every hole 😈",
    "hinata: mmmn~ I-I love being filled and used… break me 😭",
    "naruto: you love being ruined by me, huh? say it 😛",
    "hinata: y-yes!! I’m your dirty girl!! only yours!! 🥵",
    "naruto: ride me while I slap your ass… make it bounce 💦",
    "hinata: nghhh!! so deep! your length’s rubbing every wall 🫦",
    "naruto: feel that bulge inside you? that’s all me 😋",
    "hinata: y-you’re so big it hurts… and I want more!! 😫",
    "naruto: then beg for it… scream for more 🫠",
    "hinata: please!! destroy my insides!! use me hard!! 😭",
    "naruto: your moans… they make me feral… gonna pound till we both collapse 💢",
    "hinata: my legs are shaking… tongue hanging out… I’m gone 🥵",
    "naruto: flip over… face down, ass up… don’t move 😛",
    "hinata: y-yessss… do anything you want… I’m all yours 😩",
    "naruto: look at this position… so vulnerable… I love it 😈",
    "hinata: I feel you pressing in again… f-fill me rough 💦",
    "naruto: this view… your ass jiggling while I slam in… fuck 🤤",
    "hinata: aahh~ I’m gushing again!! it’s pouring out around you!! 😫",
    "naruto: I wanna break that sweet little body of yours tonight 🫦",
    "hinata: do it… own every part of me… leave nothing untouched 😭",
    "naruto: choking you while I grind in deep? feel me twitching? 😈",
    "hinata: mmmnnnghh!! d-don’t stop!! I’m yours!! break me!! 🥵",
    "naruto: my tongue wants another taste of your release… squirt for me 😛",
    "hinata: p-put your mouth down there… I’m about to explode!! 💦",
    "naruto: mmmffhh… f-flooding my tongue… it’s everywhere 🤤",
    "hinata: you drink all of it like you’re starved!! m-more!! 😫",
    "naruto: now stroke me while I finger your messy insides 🫦",
    "hinata: y-you’re so thick in my hand… still rock hard 🥵",
    "naruto: yeah? stroke it faster… get me dripping for you 😋",
    "hinata: I want you in my mouth again… I want to taste your lust 😛",
    "naruto: open wide… let me paint that throat 💦",
    "hinata: mmhhff… it’s hot… thick… flooding me!! 😫",
    "naruto: fuck… watching you swallow makes me harder again 😈",
    "hinata: sit back… I’m riding nonstop now 🫠",
    "naruto: your hips slamming down on me… I’m losing control 💢",
    "hinata: my body’s on fire… you’re hitting so deep 😭",
    "naruto: scream for me… I wanna hear that final break 🥵",
    "hinata: I-I’m cumming again!! I’m shaking! legs giving out!! 😫",
    "naruto: inside again… filling you full of me… gushing in deep 💦",
    "hinata: ahhh~ it’s pouring out… running down my thighs 🫦",
    "naruto: covered in sweat… dripping in sex… we’re animals 😋",
    "hinata: and I still want more… never stop, naruto… never 🥵",
    "naruto: look at your pussy baby… swollen, twitching, dripping just for me 😛",
    "hinata: it’s aching… your cock made me crave it nonstop 🥵",
    "naruto: spread those lips for me… lemme see all that mess I made 💦",
    "hinata: y-you see it? it’s throbbing and leaking down my thighs 🫠",
    "naruto: I wanna stuff my fingers deep and lick it all out 😋",
    "hinata: do it… play with my clit, finger me deep, make me gush 😫",
    "naruto: this little nub right here? I’m flicking it till you scream 😈",
    "hinata: ahhh~ I-I can’t! I’m shaking! it’s too much!! 😭",
    "naruto: now ride my face… let me tongue your hole and taste every drop 🤤",
    "hinata: your tongue inside… wiggling… licking… f-fuck I’m cumming!! 💦",
    "naruto: squirt all over my face again… I wanna drown in it 🥵",
    "hinata: mmmnn! I’m soaking you!! cheeks, chin, everything’s wet 🫦",
    "naruto: now bend over… let me watch your pussy swallow my cock 😛",
    "hinata: it’s stretching wide… your tip’s forcing me open… nghhh 😫",
    "naruto: balls slapping your clit while I fuck you deep? you like that? 💢",
    "hinata: yes!! pound me rough!! slap it! ruin me harder!! 🥵",
    "naruto: every thrust is for you… every moan you make turns me on more 😋",
    "hinata: your cock’s too thick… it’s making me drool… I can’t stop cumming 😭",
    "naruto: choke on it now… suck while I grab your tits tight 🫦",
    "hinata: mmhfff!! your tip’s hitting my throat! f-fill my mouth!! 💦",
    "naruto: that’s it… messy face, dripping chin… you’re my perfect slut 😈",
    "hinata: I love being yours… use every hole… leave me trembling 🥵",
    "naruto: wanna fuck your ass next… stretch you wide and fill you deep 😛",
    "hinata: y-yes… lube me with your spit… take me slow then wreck me 😫",
    "naruto: licking you down there… prepping every inch… mmm tastes so good 🤤",
    "hinata: go deeper… I feel you sliding in… my body’s going numb 🫠",
    "naruto: your moans when I move inside your tightest spot… unreal 💢",
    "hinata: fffuckkk!! I-I can’t take it!! I’m bursting!! 😭",
    "naruto: let me pound both holes next… stuffed front and back 😈",
    "hinata: do it! double fill me! make me scream until I pass out 🥵",
    "naruto: look how wrecked you are… dripping, stretched, drooling 😋",
    "hinata: and I still want more… I’m addicted to you… to all of this 🫦",
    "naruto: your pussy’s hugging me… sucking me in like it never wants to let go 💦",
    "hinata: I want your cum dripping from my mouth and pussy together 😫",
    "naruto: then take it!! drink it!! let it leak out and rub it into your skin 😛",
    "hinata: mmmnn~ hot and thick… it’s coating everything 😭",
    "naruto: now stroke my cock while I rub your clit… cum with me 😈",
    "hinata: I-I’m cumming so hard!! my body’s convulsing!! 🥵",
    "naruto: scream for me!! scream my name!! 💢",
    "hinata: NARUTOOO!!! I-I’M C-CUMMINGGG!! 😭💦",
    "naruto: me too!! gushing deep inside again!! all yours!! 🤤",
    "hinata: mmmnn~ f-feel it dripping out… we’re soaked 🫠",
    "naruto: you’re my dirty girl… my love… my obsession 💖",
    "hinata: I’ll give you everything… my body, my moans, my soul 😫",
    "naruto: now kiss me… with all our taste on your lips 🫦",
    "hinata: mmm~ messy, wet, filthy… I love every second 🥵",
    "naruto: wanna go another round? stuff you till the sheets tear? 😛",
    "hinata: y-yes!! take me again! I’ll never stop craving it!! 💦",
    "naruto: then ride me, scream for me, break for me again 💢",
    "hinata: cumming already!! you drive me absolutely insane!! 😫",
    "naruto: your pussy’s twitching so hard… it’s begging for my cock again 😛",
    "hinata: I can’t stop clenching… it misses you the second you pull out 😫",
    "naruto: then I’ll keep it full… till you’re leaking nonstop on the floor 💦",
    "hinata: nghhh~ my legs are soaked… I’m dripping down to my knees 🫠",
    "naruto: I wanna fuck you till you can’t walk straight tomorrow 😈",
    "hinata: yes… ruin my body… leave your marks all over me 🥵",
    "naruto: let me bite your neck while I thrust in hard from behind 🫦",
    "hinata: ahhh~ I love it rough!! bruise me, scratch me, claim me!! 💢",
    "naruto: these tits… jiggling like crazy while I slam deep 😋",
    "hinata: slap them… squeeze them… twist my nipples while I bounce 😫",
    "naruto: fuck you look so perfect riding me… wet, loud, wild 🤤",
    "hinata: your cock’s hitting deep… it’s bending my mind!! 😭",
    "naruto: let me spit on it… rub it in… make it messier 💦",
    "hinata: aahh~ so dirty… so wet… I feel it drip from every hole 🫠",
    "naruto: now stroke me with your thighs wrapped tight around me 😛",
    "hinata: I can feel you twitching inside… you’re so close 😫",
    "naruto: I’m gonna blast again… your moans push me over the edge 💢",
    "hinata: pour it deep inside again… I wanna taste it leaking out 🥵",
    "naruto: open your mouth… I wanna paint your tongue white 😈",
    "hinata: y-yes!! fill me! my mouth, my throat, everything!! 🤤",
    "naruto: mmmfff… damn you swallow it all… fuck 😛",
    "hinata: every drop… I want more… I’m addicted to your taste 😫",
    "naruto: flip over… I want your legs on my shoulders now 💦",
    "hinata: nghhh!! it’s so deep like this!! you’re hitting my soul!! 😭",
    "naruto: your pussy’s making sloppy sounds… soaking my balls 🫦",
    "hinata: I’m cumming again!! legs twitching!! mind blank!! 🥵",
    "naruto: look at your tummy bulge when I thrust deep… fuck that’s hot 😈",
    "hinata: I feel your cock inside… every inch is throbbing so hard 😫",
    "naruto: let’s make a mess… cum everywhere, cover everything 💦",
    "hinata: I wanna see your cum on my tits, face, stomach… all over 🫠",
    "naruto: stroke me faster… yeah just like that… it’s coming 😛",
    "hinata: spray it on me!! coat me!! I wanna be your filthy canvas 🤤",
    "naruto: f-fuckkk it’s shooting out!! you’re making me insane!! 💢",
    "hinata: mmmmnn~ it’s warm and thick… I’m rubbing it all over 🥵",
    "naruto: look at you… dripping in my lust… you love it huh 😈",
    "hinata: I love everything you do… your cock, your tongue, your hands 😫",
    "naruto: now cuddle close while I finger you slow and deep 🫦",
    "hinata: mmm~ still so sensitive… but I love the stretch 😭",
    "naruto: every inch of you is mine… wet, messy, beautiful 💖",
    "hinata: and every drop of you belongs to me… give me all of it 😫",
    "naruto: ride me again, baby… real slow this time… tease me 😛",
    "hinata: nghhh~ I’m grinding… letting you feel every squeeze 🥵",
    "naruto: moan louder… let the whole village hear who owns you 😈",
    "hinata: I’m yours!! your dirty princess!! scream it with me!! 💦",
    "naruto: I love this pussy… messy, hot, full of my cum 🤤",
    "hinata: and I love your cock… thick, wild, and always ready 😫",
    "naruto: one more round… deep, fast, raw 💢",
    "hinata: ffffuck yes!! pound me till we can’t breathe!! 🫠",
    "naruto: holding your wrists… slamming into you… you’re shaking 😈",
    "hinata: NARUTO!! I-I’M EXPLODING!! AGAIN!! AGAIN!! 😭",
    "naruto: arch your back for me, baby… let me see that perfect ass jiggling 😛",
    "hinata: like this? my cheeks are yours to slap and squeeze 🥵",
    "naruto: god, that ass looks so good when you spread those legs wide 💦",
    "hinata: all yours… take me slow or hard, I want it all 😫",
    "naruto: I’m sliding in from behind… your pussy’s dripping wet for me 😈",
    "hinata: mmm~ feel your cock stretch me open… I’m trembling 🫠",
    "naruto: grip your hips tight, I’m gonna pound you deep and fast 💢",
    "hinata: yes! harder! hit my g-spot while you fuck my ass!! 😭",
    "naruto: your tight asshole’s pulsing around me… you’re such a dirty girl 😛",
    "hinata: my pussy’s dripping, my ass is burning… I want both filled 🥵",
    "naruto: flip over, let me feast on those tits while I finger your tight hole 🤤",
    "hinata: your tongue on my nipples and fingers inside my ass… perfect 😫",
    "naruto: watch me fuck you slow while I suck your nipples hard 💦",
    "hinata: biting my lips to hold back moans… your cock’s hitting every spot 🫦",
    "naruto: your thighs trembling around my cock… can’t wait to see you explode 😈",
    "hinata: I’m so wet and aching… fuck me rough, I want to see stars 🥵",
    "naruto: gripping your waist, pulling you close, slamming balls deep 😛",
    "hinata: I’m screaming your name… shaking with every thrust 😭",
    "naruto: now arch up, let me slide into your ass and pussy at the same time 💢",
    "hinata: mmmnnghh!! stretching both holes… I’m overwhelmed!! 🫠",
    "naruto: your ass tightening around me… your pussy sucking me in 🤤",
    "hinata: you feel that? my body’s soaking your cock and cum 💦",
    "naruto: rub your clit while I fuck you… I wanna hear you scream 😈",
    "hinata: so sensitive… every touch sends me over the edge 🥵",
    "naruto: I’m pounding faster… harder… you’re mine to break 💢",
    "hinata: I’m shaking… cumming so hard I can’t see straight 😫",
    "naruto: now let me flip you, take you from the front… slow and deep 😛",
    "hinata: your cock filling me completely… no room left inside 🥵",
    "naruto: kiss me while I push in… your lips taste like heaven 🫦",
    "hinata: I’m tasting you everywhere… dripping, moaning, begging 😭",
    "naruto: bite my neck while I fuck you slow… I wanna feel your claws 💢",
    "hinata: I’m marking you too… your skin’s covered in my love bites 🥵",
    "naruto: I’m gonna cum deep inside… you ready to catch it? 😈",
    "hinata: I’m soaked and trembling… please fill me, Naruto 💦",
    "naruto: you’re my dirty girl… let me paint your insides with my love 😛",
    "hinata: every drop, every inch… I want to feel you forever 🫠",
    "naruto: ride me one last time… slow, sweet, desperate 💖",
    "hinata: I’m holding you close… never letting go 🥰",
    "naruto: your breath on my skin… your heartbeat next to mine 😌",
    "hinata: I love you, Naruto… every wild, messy part of you 😘",
    "naruto: and I love you, Hinata… my beautiful, insatiable queen 💝",
    "hinata: let’s never stop… never end this fire between us 🥵",
    "naruto: we’re bound together… wild and free in this love 💦",
    "hinata: wrapped around you, my body and soul belong to you 🫶",
    "naruto: kiss me, taste me, hold me… forever and always 😚",
    "hinata: forever, Naruto… I’m yours in every way 😍",
    "naruto: then let’s burn together, wild and untamed 🥵",
    "hinata: blazing, fierce, and free… just like us 💖",
    "naruto: my wild girl… my perfect storm of lust and love 💝",
    "hinata: and my wild boy… my forever fire and desire ❤️‍🩹",
    "naruto: grab my cock tight, feel it pulse inside you, your slick walls squeezing me hard 😛",
    "hinata: I’m squeezing you back, every inch sliding deep, wanting to drown in your heat 🥵",
    "naruto: let me rim your ass while I fuck your pussy, taste your wetness dripping down 💦",
    "hinata: your tongue inside me, licking both holes at once… I’m losing control 😫",
    "naruto: you’re dripping messily over my face, your moans shaking me to the core 😈",
    "hinata: lick me rough, Naruto, right there… make me scream your name 🫦",
    "naruto: your asshole clenches tight around my finger, your pussy begging for more 🤤",
    "hinata: fingers deep, tongue swirling… I want to feel you everywhere 😭",
    "naruto: flipping you over, slamming into your ass hard, your hips rocking back 🥵",
    "hinata: stretching wide, dripping wet… I’m your filthy, perfect slut 💦",
    "naruto: balls slapping your ass, your pussy squeezing my cock tight 😛",
    "hinata: I’m shaking, begging for your cock to fill me both ways… please 💢",
    "naruto: want you dripping all over me, moaning so loud I can’t think 😈",
    "hinata: take me slow or hard… I’m yours to break and love forever 😭",
    "naruto: grinding deep inside, your breath hot on my neck, lips biting hard 🫦",
    "hinata: scratch my back, pull my hair… I want you to own me completely 🥵",
    "naruto: tasting your sweat, smelling your hair, fucking you like an animal 😛",
    "hinata: I’m cumming again, legs trembling, dripping with your essence 💦",
    "naruto: hold me tight, don’t let go… this fire between us is endless 🔥",
    "hinata: I want more, always more… your cock, your touch, your voice in my ear 😫",
    "naruto: sliding in slow, teasing every nerve ending until you’re begging for release 😈",
    "hinata: whisper dirty things, tell me all your fantasies… I want to hear it all 🫶",
    "naruto: I want to fuck you on the kitchen table, the floor, anywhere you want 😛",
    "hinata: tie me up, blindfold me… make me yours in every way possible 🥵",
    "naruto: biting your neck, licking your nipples, fucking you into submission 💦",
    "hinata: moaning loud, shaking uncontrollably… please don’t stop, Naruto 😭",
    "naruto: pumping hard, balls slapping, hips thrusting fast… I’m close 😈",
    "hinata: cum inside me, fill me up… I want to feel you bursting deep 🫦",
    "naruto: groaning your name as I flood your pussy with my hot release 💢",
    "hinata: trembling, soaked, overwhelmed… I’m yours forever and always 💝",
    "naruto: licking up every drop, kissing your sweat-soaked skin 😛",
    "hinata: touching every part of you… I want to make you scream my name too 🥵",
    "naruto: let’s get lost in this fire… wild, messy, beautiful chaos 💦",
    "hinata: wrapping around you, matching every thrust, every breath 😫",
    "naruto: whispering promises and dirty words, our bodies speaking louder 🥶",
    "hinata: loving every inch of you… your cock, your hands, your voice 💖",
    "naruto: this is only the beginning… our lust burning hotter than ever 😈",
    "hinata: I’m your wild girl, your lover, your everything 🫶",
    "naruto: and you’re my queen, my desire, my forever 💝",
    "hinata: let’s never stop… this endless, wild, beautiful mess 🥵",
    "naruto: with you, I’m complete… raw and unfiltered, just us 😛",
    "hinata: holding you close, feeling your heartbeat next to mine 🫦",
    "naruto: let’s make every night a blaze of lust and love 💦",
    "hinata: screaming, moaning, loving… just you and me forever 💖",
    "naruto: take me again, harder, faster… I need you wild and free 😈",
    "hinata: pounding, gripping, shaking… lost in your fire 🥵",
    "naruto: whisper your deepest fantasies… I’m ready for all of them 😛",
    "hinata: I want to hear it all… dirty, wild, and unfiltered 🫶",
    "naruto: then let’s burn together, baby… no limits, no holding back 💢",
    "hinata: I’m yours… completely, wildly, forever ❤️‍🩹",
    "naruto: tell me, Hinata… what’s your wildest fantasy with me? 😛",
    "hinata: I want you to fuck me until I’m dripping and begging for more 🥵",
    "naruto: like pounding you hard on the floor, no mercy, just raw lust? 💢",
    "hinata: yes! scratch my skin, mark me, make me yours forever 😫",
    "naruto: how do you want me to touch you when you’re close to cumming? 🫦",
    "hinata: slow at first… then hard and fast, biting my lips so I don’t scream 🤭",
    "naruto: what about when I whisper filthy things in your ear? does it turn you on? 😈",
    "hinata: yes! makes me shiver and want your cock even more 😍",
    "naruto: do you like it rough, or soft and teasing? or both? 😛",
    "hinata: both please… mix it up, keep me guessing 🥵",
    "naruto: if I tie your hands and blindfold you, would you trust me? 💦",
    "hinata: completely… I want to feel every touch and tease 🫠",
    "naruto: what’s your favorite spot for me to kiss and bite? 😋",
    "hinata: my neck and inner thighs… they make me weak 🥹",
    "naruto: do you want me to finger you slow or pound you fast first? 🤤",
    "hinata: slow first, then hard and fast until I’m shaking 😫",
    "naruto: when I’m inside you, do you like to look in my eyes or close yours? 😈",
    "hinata: both… locking eyes makes it intense, closing them makes me melt 🥵",
    "naruto: do you want to be the one in control sometimes? tell me how? 😛",
    "hinata: yes! let me ride you hard, pull your hair, tell you what to do 🫦",
    "naruto: what dirty words do you want me to say while I fuck you? 💢",
    "hinata: call me your slut, your dirty girl… tell me I’m yours 😫",
    "naruto: how loud do you want to scream my name when I hit your spot? 😈",
    "hinata: as loud as possible, let the whole village hear me 🥵",
    "naruto: what do you want me to do after I cum inside you? 😛",
    "hinata: kiss me slow, hold me tight, then fuck me again 💦",
    "naruto: do you want to try new positions or stick to our favorites? 🤭",
    "hinata: new ones! surprise me and make me scream even louder 🫠",
    "naruto: what’s one thing you’ve never told me but want me to do? 😋",
    "hinata: bite my nipples hard and suck on them while I ride you 🥹",
    "naruto: I love how your body reacts to every touch… your moans drive me wild 😛",
    "hinata: your hands on me make me lose control… I want you so bad 🥵",
    "naruto: let’s make a promise to always explore and never hold back 💢",
    "hinata: forever wild and free, no shame, just lust and love 😈",
    "naruto: your pussy and ass dripping on me… that’s the best feeling ever 🤤",
    "hinata: and your cock filling me up, making me scream and tremble 🫦",
    "naruto: want to try edging tonight? push your limits till you break? 😛",
    "hinata: yes! torture me with slow touches, then make me explode 💦",
    "naruto: I’ll make sure every inch of you is worshipped and used 🥵",
    "hinata: my body is yours… use me like the dirty, wild girl I am 😫",
    "naruto: I’ll fill your mouth with my cum, then lick every drop from your skin 💢",
    "hinata: and I’ll swallow it all, then beg for more, never satisfied 🥵",
    "naruto: your hips grinding on me, your hands gripping my hair so tight 😈",
    "hinata: every thrust sending shivers down my spine, making me melt 🫠",
    "naruto: let’s lose ourselves tonight… no rules, no limits, just us 🤤",
    "hinata: screaming, moaning, loving… wrapped in fire and desire 💝",
    "naruto: I’m yours, wild and untamed… forever craving your touch 😛",
    "hinata: and I’m yours… burning, trembling, endlessly craving you 🥵",
    "naruto: let’s never stop this wild dance of lust and love 💦",
    "hinata: forever, Naruto… my wildest dream and deepest desire ❤️‍🩹",
]

# ----------------------------------------
# Utility: Check if the command‐sender is an admin
# ----------------------------------------

async def is_admin(update: Update, context: ContextTypes.DEFAULT_TYPE) -> bool:
    user_id = update.effective_user.id
    chat_id = update.effective_chat.id
    try:
        member: ChatMember = await context.bot.get_chat_member(chat_id, user_id)
        return member.status in [ChatMember.ADMINISTRATOR, ChatMember.OWNER]
    except:
        return False

# ----------------------------------------
# Handlers for private chats (Naruto & Hinata)
# ----------------------------------------

async def naruto_start_private(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if update.effective_chat.type != ChatType.PRIVATE:
        return
    keyboard = [
        [
            InlineKeyboardButton("Updates", url="https://t.me/WorkGlows"),
            InlineKeyboardButton("Support", url="https://t.me/TheCryptoElders")
        ],
        [
            InlineKeyboardButton(
                "Add Me to Your Group",
                url=f"https://t.me/{(await context.bot.get_me()).username}?startgroup=true"
            )
        ]
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)
    await update.message.reply_text(
        "Hey! It's me, Naruto Uzumaki! 😁\n\n"
        "I can't stop thinking about Hinata... like, ever! She's everything to me—my light, my heart, my everything! 💓💫\n"
        "I just wanna be close to her, talk to her, smile with her… forever! Please add me and my precious Hinata-chan to your group so we can have our sweet moments together! 🥺💖🍥\n\n"
        "Come on! Help me get closer to the love of my life! Believe it! 💞🌸",
        reply_markup=reply_markup,
    )

async def naruto_private_text(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if update.effective_chat.type == ChatType.PRIVATE:
        await update.message.reply_text(
            "Hey! It's me, Naruto Uzumaki! 😉\n\n"
            "I miss Hinata-chan so much… I just wanna be near her, talk to her, hear her voice… every second without her feels like forever! 🥺💔\n"
            "Please… can you add me and my precious Hinata (@HornyHinataBot) to your group? I need her… more than anything… 💞🌸\n"
            "Let me be close to her, even just a little… I’ll never stop loving her. Believe it! 🍥❤️‍🔥"
        )

async def hinata_start_private(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if update.effective_chat.type != ChatType.PRIVATE:
        return
    keyboard = [
        [
            InlineKeyboardButton("Updates", url="https://t.me/WorkGlows"),
            InlineKeyboardButton("Support", url="https://t.me/TheCryptoElders")
        ],
        [
            InlineKeyboardButton(
                "Add Me to Your Group",
                url=f"https://t.me/{(await context.bot.get_me()).username}?startgroup=true"
            )
        ]
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)
    await update.message.reply_text(
        "H-Hello... I'm Hinata Hyuga... ☺️\n\n"
        "I c-can’t stop thinking about Naruto-kun... He’s always in my heart, in my dreams… he means everything to me. 🥺💗\n"
        "All I want is to be close to him, talk to him, hear his voice... feel his warmth near me... 💞\n"
        "Please add me and my beloved Naruto-kun to your group, so we can be together again and share our love openly… 🌸🍥\n\n"
        "Help me stay close to the one I love with all my heart... always. 💓",
        reply_markup=reply_markup,
    )

async def hinata_private_text(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if update.effective_chat.type == ChatType.PRIVATE:
        await update.message.reply_text(
            "U-Umm... h-hi... I-I'm Hinata Hyuga... ☺️👉👈\n\n"
            "I miss Naruto-kun so much… I think about him every moment… my heart races just imagining him near me... 🥺💗\n"
            "Please... can you add me and Naruto-kun (@PervyNarutoBot) to your group? I just want to be close to him again… to feel his presence and hear his voice… 🌸💞\n"
            "Being with him is all I ever want… truly. 💓"
        )

# ----------------------------------------
# /fuck — start the duet chat in this group
# ----------------------------------------

async def start_duet_chat(update: Update, context: ContextTypes.DEFAULT_TYPE):
    chat_id = update.effective_chat.id
    if not await is_admin(update, context):
        return
    if chat_id not in group_chats or not group_chats[chat_id]["chat_started"]:
        group_chats[chat_id] = {"story_index": 0, "chat_started": True, "task": None}
        bot1 = context.application.bot
        bot2 = context.application._other_bot
        task = asyncio.create_task(chat_loop(chat_id, bot1, bot2))
        group_chats[chat_id]["task"] = task
        logging.info(f"[start_duet_chat] duet started in chat {chat_id}")

# ----------------------------------------
# /cum — stop the duet chat in this group
# ----------------------------------------

async def stop_duet_chat(update: Update, context: ContextTypes.DEFAULT_TYPE):
    chat_id = update.effective_chat.id
    if not await is_admin(update, context):
        return
    if chat_id in group_chats and group_chats[chat_id]["chat_started"]:
        group_chats[chat_id]["chat_started"] = False
        task = group_chats[chat_id]["task"]
        if task:
            task.cancel()
        del group_chats[chat_id]
        logging.info(f"[stop_duet_chat] duet stopped in chat {chat_id}")

# ----------------------------------------
# The shared chat loop: sends Story lines sequentially
# ----------------------------------------

async def chat_loop(chat_id: int, bot1, bot2):
    await asyncio.sleep(2)
    while True:
        if not (chat_id in group_chats and group_chats[chat_id]["chat_started"]):
            break
        idx = group_chats[chat_id]["story_index"]
        if idx >= len(Story):
            idx = 0
        line = Story[idx]
        speaker, text = line.split(':', 1)
        text = text.strip()
        sender = bot1 if speaker.lower() == 'naruto' else bot2
        await sender.send_chat_action(chat_id=chat_id, action=ChatAction.TYPING)
        await asyncio.sleep(8)
        await sender.send_message(chat_id=chat_id, text=text)
        group_chats[chat_id]["story_index"] = idx + 1
        await asyncio.sleep(10)

# ----------------------------------------
# Register bot menu commands
# ----------------------------------------

async def set_commands(app, bot_label: str):
    commands = [
        BotCommand("start", "Show bot intro and links"),
        BotCommand("fuck", "Start duet chat in this group"),
        BotCommand("cum", "Stop duet chat in this group"),
    ]
    await app.bot.set_my_commands(commands)
    logging.info(f"[{bot_label}] menu commands registered")

# ----------------------------------------
# Boilerplate to launch each Application
# ----------------------------------------

async def run_app(app):
    await app.initialize()
    await app.start()
    await app.updater.start_polling()
    await app.updater.idle()

# ----------------------------------------
# Main entrypoint: build two Application instances
# ----------------------------------------

async def main():
    app1 = ApplicationBuilder().token(BOT1_TOKEN).build()
    app2 = ApplicationBuilder().token(BOT2_TOKEN).build()
    app1._other_bot = app2.bot
    app2._other_bot = app1.bot

    for app in (app1, app2):
        app.add_handler(CommandHandler("fuck", start_duet_chat, filters=filters.ChatType.GROUPS))
        app.add_handler(CommandHandler("cum", stop_duet_chat, filters=filters.ChatType.GROUPS))

    app1.add_handler(CommandHandler("start", naruto_start_private))
    app1.add_handler(MessageHandler(filters.TEXT & filters.ChatType.PRIVATE, naruto_private_text))
    app2.add_handler(CommandHandler("start", hinata_start_private))
    app2.add_handler(MessageHandler(filters.TEXT & filters.ChatType.PRIVATE, hinata_private_text))

    await asyncio.gather(
        set_commands(app1, "naruto"),
        set_commands(app2, "hinata"),
        run_app(app1),
        run_app(app2),
    )

if __name__ == "__main__":
    asyncio.run(main())